#if (GL_ARB_SHADER_ATOMIC_COUNTERS || GL_ES_VERSION_3_1 || GL_VERSION_4_2 || GL_ARB_COMPUTE_SHADER || GL_VERSION_4_3)

public enum AtomicCounterBufferPName : GLenum { 
#if (GL_ARB_SHADER_ATOMIC_COUNTERS || GL_ES_VERSION_3_1 || GL_VERSION_4_2)
    Binding = gl.Constants.GL_ATOMIC_COUNTER_BUFFER_BINDING, 
#endif

#if (GL_ARB_SHADER_ATOMIC_COUNTERS || GL_VERSION_4_2)
    DataSize = gl.Constants.GL_ATOMIC_COUNTER_BUFFER_DATA_SIZE, 
#endif

#if (GL_ARB_SHADER_ATOMIC_COUNTERS || GL_VERSION_4_2)
    ActiveAtomicCounters = gl.Constants.GL_ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTERS, 
#endif

#if (GL_ARB_SHADER_ATOMIC_COUNTERS || GL_VERSION_4_2)
    ActiveAtomicCounterIndices = gl.Constants.GL_ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTER_INDICES, 
#endif

#if (GL_ARB_SHADER_ATOMIC_COUNTERS || GL_VERSION_4_2)
    ReferencedByVertexShader = gl.Constants.GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_VERTEX_SHADER, 
#endif

#if (GL_ARB_SHADER_ATOMIC_COUNTERS || GL_VERSION_4_2)
    ReferencedByTessControlShader = gl.Constants.GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_TESS_CONTROL_SHADER, 
#endif

#if (GL_ARB_SHADER_ATOMIC_COUNTERS || GL_VERSION_4_2)
    ReferencedByTessEvaluationShader = gl.Constants.GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_TESS_EVALUATION_SHADER, 
#endif

#if (GL_ARB_SHADER_ATOMIC_COUNTERS || GL_VERSION_4_2)
    ReferencedByGeometryShader = gl.Constants.GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_GEOMETRY_SHADER, 
#endif

#if (GL_ARB_SHADER_ATOMIC_COUNTERS || GL_VERSION_4_2)
    ReferencedByFragmentShader = gl.Constants.GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_FRAGMENT_SHADER, 
#endif

#if (GL_ARB_COMPUTE_SHADER || GL_VERSION_4_3)
    ReferencedByComputeShader = gl.Constants.GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_COMPUTE_SHADER, 
#endif

}

#endif
