#if (GL_ES_VERSION_2_0 || GL_EXT_DRAW_BUFFERS_INDEXED || GL_NV_BLEND_EQUATION_ADVANCED || GL_NV_REGISTER_COMBINERS || GL_OES_DRAW_BUFFERS_INDEXED || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0 || GL_ARB_IMAGING || GL_VERSION_1_4 || GL_ARB_BLEND_FUNC_EXTENDED || GL_VERSION_1_5 || GL_VERSION_3_3)

public enum BlendingFactor : GLenum { 
#if (GL_ES_VERSION_2_0 || GL_EXT_DRAW_BUFFERS_INDEXED || GL_NV_BLEND_EQUATION_ADVANCED || GL_NV_REGISTER_COMBINERS || GL_OES_DRAW_BUFFERS_INDEXED || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0)
    Zero = gl.Constants.GL_ZERO, 
#endif

#if (GL_ES_VERSION_2_0 || GL_EXT_DRAW_BUFFERS_INDEXED || GL_OES_DRAW_BUFFERS_INDEXED || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0)
    One = gl.Constants.GL_ONE, 
#endif

#if (GL_ES_VERSION_2_0 || GL_EXT_DRAW_BUFFERS_INDEXED || GL_OES_DRAW_BUFFERS_INDEXED || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0)
    SrcColor = gl.Constants.GL_SRC_COLOR, 
#endif

#if (GL_ES_VERSION_2_0 || GL_EXT_DRAW_BUFFERS_INDEXED || GL_OES_DRAW_BUFFERS_INDEXED || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0)
    OneMinusSrcColor = gl.Constants.GL_ONE_MINUS_SRC_COLOR, 
#endif

#if (GL_ES_VERSION_2_0 || GL_EXT_DRAW_BUFFERS_INDEXED || GL_OES_DRAW_BUFFERS_INDEXED || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0)
    SrcAlpha = gl.Constants.GL_SRC_ALPHA, 
#endif

#if (GL_ES_VERSION_2_0 || GL_EXT_DRAW_BUFFERS_INDEXED || GL_OES_DRAW_BUFFERS_INDEXED || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0)
    OneMinusSrcAlpha = gl.Constants.GL_ONE_MINUS_SRC_ALPHA, 
#endif

#if (GL_ES_VERSION_2_0 || GL_EXT_DRAW_BUFFERS_INDEXED || GL_OES_DRAW_BUFFERS_INDEXED || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0)
    DstAlpha = gl.Constants.GL_DST_ALPHA, 
#endif

#if (GL_ES_VERSION_2_0 || GL_EXT_DRAW_BUFFERS_INDEXED || GL_OES_DRAW_BUFFERS_INDEXED || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0)
    OneMinusDstAlpha = gl.Constants.GL_ONE_MINUS_DST_ALPHA, 
#endif

#if (GL_ES_VERSION_2_0 || GL_EXT_DRAW_BUFFERS_INDEXED || GL_OES_DRAW_BUFFERS_INDEXED || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0)
    DstColor = gl.Constants.GL_DST_COLOR, 
#endif

#if (GL_ES_VERSION_2_0 || GL_EXT_DRAW_BUFFERS_INDEXED || GL_OES_DRAW_BUFFERS_INDEXED || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0)
    OneMinusDstColor = gl.Constants.GL_ONE_MINUS_DST_COLOR, 
#endif

#if (GL_ES_VERSION_2_0 || GL_EXT_DRAW_BUFFERS_INDEXED || GL_OES_DRAW_BUFFERS_INDEXED || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0)
    SrcAlphaSaturate = gl.Constants.GL_SRC_ALPHA_SATURATE, 
#endif

#if (GL_ARB_IMAGING || GL_ES_VERSION_2_0 || GL_EXT_DRAW_BUFFERS_INDEXED || GL_OES_DRAW_BUFFERS_INDEXED || GL_SC_VERSION_2_0 || GL_VERSION_1_4)
    ConstantColor = gl.Constants.GL_CONSTANT_COLOR, 
#endif

#if (GL_ARB_IMAGING || GL_ES_VERSION_2_0 || GL_EXT_DRAW_BUFFERS_INDEXED || GL_OES_DRAW_BUFFERS_INDEXED || GL_SC_VERSION_2_0 || GL_VERSION_1_4)
    OneMinusConstantColor = gl.Constants.GL_ONE_MINUS_CONSTANT_COLOR, 
#endif

#if (GL_ARB_IMAGING || GL_ES_VERSION_2_0 || GL_EXT_DRAW_BUFFERS_INDEXED || GL_OES_DRAW_BUFFERS_INDEXED || GL_SC_VERSION_2_0 || GL_VERSION_1_4)
    ConstantAlpha = gl.Constants.GL_CONSTANT_ALPHA, 
#endif

#if (GL_ARB_IMAGING || GL_ES_VERSION_2_0 || GL_EXT_DRAW_BUFFERS_INDEXED || GL_OES_DRAW_BUFFERS_INDEXED || GL_SC_VERSION_2_0 || GL_VERSION_1_4)
    OneMinusConstantAlpha = gl.Constants.GL_ONE_MINUS_CONSTANT_ALPHA, 
#endif

#if (GL_ARB_BLEND_FUNC_EXTENDED || GL_VERSION_1_5 || GL_VERSION_ES_CM_1_0)
    Src1Alpha = gl.Constants.GL_SRC1_ALPHA, 
#endif

#if (GL_ARB_BLEND_FUNC_EXTENDED || GL_VERSION_3_3)
    Src1Color = gl.Constants.GL_SRC1_COLOR, 
#endif

#if (GL_ARB_BLEND_FUNC_EXTENDED || GL_VERSION_3_3)
    OneMinusSrc1Color = gl.Constants.GL_ONE_MINUS_SRC1_COLOR, 
#endif

#if (GL_ARB_BLEND_FUNC_EXTENDED || GL_VERSION_3_3)
    OneMinusSrc1Alpha = gl.Constants.GL_ONE_MINUS_SRC1_ALPHA, 
#endif

}

#endif
