#if (GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_1_5 || GL_VERSION_ES_CM_1_0 || GL_ES_VERSION_3_0 || GL_VERSION_2_1 || GL_ARB_UNIFORM_BUFFER_OBJECT || GL_VERSION_3_1 || GL_ARB_ENHANCED_LAYOUTS || GL_VERSION_3_0 || GL_VERSION_4_4 || GL_ARB_COPY_BUFFER || GL_ARB_DRAW_INDIRECT || GL_ES_VERSION_3_1 || GL_VERSION_4_0 || GL_ARB_SHADER_STORAGE_BUFFER_OBJECT || GL_VERSION_4_3 || GL_ARB_COMPUTE_SHADER || GL_ARB_PROGRAM_INTERFACE_QUERY || GL_ARB_SHADER_ATOMIC_COUNTERS || GL_VERSION_4_2 || GL_ARB_INTERNALFORMAT_QUERY2 || GL_ES_VERSION_3_2 || GL_ARB_QUERY_BUFFER_OBJECT)

public enum CopyBufferSubDataTarget : GLenum { 
#if (GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_1_5 || GL_VERSION_ES_CM_1_0)
    ArrayBuffer = gl.Constants.GL_ARRAY_BUFFER, 
#endif

#if (GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_1_5 || GL_VERSION_ES_CM_1_0)
    ElementArrayBuffer = gl.Constants.GL_ELEMENT_ARRAY_BUFFER, 
#endif

#if (GL_ES_VERSION_3_0 || GL_VERSION_2_1)
    PixelPackBuffer = gl.Constants.GL_PIXEL_PACK_BUFFER, 
#endif

#if (GL_ES_VERSION_3_0 || GL_VERSION_2_1)
    PixelUnpackBuffer = gl.Constants.GL_PIXEL_UNPACK_BUFFER, 
#endif

#if (GL_ARB_UNIFORM_BUFFER_OBJECT || GL_ES_VERSION_3_0 || GL_VERSION_3_1)
    UniformBuffer = gl.Constants.GL_UNIFORM_BUFFER, 
#endif

#if (GL_ARB_ENHANCED_LAYOUTS || GL_ES_VERSION_3_0 || GL_VERSION_3_0 || GL_VERSION_4_4)
    TransformFeedbackBuffer = gl.Constants.GL_TRANSFORM_FEEDBACK_BUFFER, 
#endif

#if (GL_ARB_COPY_BUFFER || GL_ES_VERSION_3_0 || GL_VERSION_3_1)
    ReadBuffer = gl.Constants.GL_COPY_READ_BUFFER, 
#endif

#if (GL_ARB_COPY_BUFFER || GL_ES_VERSION_3_0 || GL_VERSION_3_1)
    WriteBuffer = gl.Constants.GL_COPY_WRITE_BUFFER, 
#endif

#if (GL_ARB_DRAW_INDIRECT || GL_ES_VERSION_3_1 || GL_VERSION_4_0)
    DrawIndirectBuffer = gl.Constants.GL_DRAW_INDIRECT_BUFFER, 
#endif

#if (GL_ARB_SHADER_STORAGE_BUFFER_OBJECT || GL_ES_VERSION_3_1 || GL_VERSION_4_3)
    ShaderStorageBuffer = gl.Constants.GL_SHADER_STORAGE_BUFFER, 
#endif

#if (GL_ARB_COMPUTE_SHADER || GL_ES_VERSION_3_1 || GL_VERSION_4_3)
    DispatchIndirectBuffer = gl.Constants.GL_DISPATCH_INDIRECT_BUFFER, 
#endif

#if (GL_ARB_PROGRAM_INTERFACE_QUERY || GL_ARB_SHADER_ATOMIC_COUNTERS || GL_ES_VERSION_3_1 || GL_VERSION_4_2)
    AtomicCounterBuffer = gl.Constants.GL_ATOMIC_COUNTER_BUFFER, 
#endif

#if (GL_ARB_INTERNALFORMAT_QUERY2 || GL_ES_VERSION_3_2 || GL_VERSION_3_1)
    TextureBuffer = gl.Constants.GL_TEXTURE_BUFFER, 
#endif

#if (GL_ARB_QUERY_BUFFER_OBJECT || GL_VERSION_4_4)
    QueryBuffer = gl.Constants.GL_QUERY_BUFFER, 
#endif

}

#endif
