#if (GL_ARB_INTERNALFORMAT_QUERY2 || GL_ES_VERSION_2_0 || GL_EXT_SPARSE_TEXTURE || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0 || GL_VERSION_1_3 || GL_ARB_FRAMEBUFFER_OBJECT || GL_NV_INTERNALFORMAT_SAMPLE_QUERY || GL_VERSION_3_0 || GL_ES_VERSION_3_0 || GL_VERSION_1_2 || GL_ARB_TEXTURE_MULTISAMPLE || GL_ES_VERSION_3_1 || GL_VERSION_3_2 || GL_ES_VERSION_3_2 || GL_VERSION_4_0 || GL_VERSION_3_1)

public enum CopyImageSubDataTarget : GLenum { 
#if (GL_ARB_INTERNALFORMAT_QUERY2 || GL_ES_VERSION_2_0 || GL_EXT_SPARSE_TEXTURE || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0)
    Texture2D = gl.Constants.GL_TEXTURE_2D, 
#endif

#if (GL_ARB_INTERNALFORMAT_QUERY2 || GL_ES_VERSION_2_0 || GL_EXT_SPARSE_TEXTURE || GL_VERSION_1_3)
    TextureCubeMap = gl.Constants.GL_TEXTURE_CUBE_MAP, 
#endif

#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ARB_INTERNALFORMAT_QUERY2 || GL_ES_VERSION_2_0 || GL_NV_INTERNALFORMAT_SAMPLE_QUERY || GL_SC_VERSION_2_0 || GL_VERSION_3_0)
    Renderbuffer = gl.Constants.GL_RENDERBUFFER, 
#endif

#if (GL_ARB_INTERNALFORMAT_QUERY2 || GL_ES_VERSION_3_0 || GL_EXT_SPARSE_TEXTURE || GL_VERSION_1_2)
    Texture3D = gl.Constants.GL_TEXTURE_3D, 
#endif

#if (GL_ARB_INTERNALFORMAT_QUERY2 || GL_ES_VERSION_3_0 || GL_EXT_SPARSE_TEXTURE || GL_VERSION_3_0)
    Texture2DArray = gl.Constants.GL_TEXTURE_2D_ARRAY, 
#endif

#if (GL_ARB_INTERNALFORMAT_QUERY2 || GL_ARB_TEXTURE_MULTISAMPLE || GL_ES_VERSION_3_1 || GL_NV_INTERNALFORMAT_SAMPLE_QUERY || GL_VERSION_3_2)
    Texture2DMultisample = gl.Constants.GL_TEXTURE_2D_MULTISAMPLE, 
#endif

#if (GL_ARB_INTERNALFORMAT_QUERY2 || GL_ES_VERSION_3_2 || GL_VERSION_4_0)
    TextureCubeMapArray = gl.Constants.GL_TEXTURE_CUBE_MAP_ARRAY, 
#endif

#if (GL_ARB_INTERNALFORMAT_QUERY2 || GL_ARB_TEXTURE_MULTISAMPLE || GL_ES_VERSION_3_2 || GL_NV_INTERNALFORMAT_SAMPLE_QUERY || GL_VERSION_3_2)
    Texture2DMultisampleArray = gl.Constants.GL_TEXTURE_2D_MULTISAMPLE_ARRAY, 
#endif

#if (GL_ARB_INTERNALFORMAT_QUERY2 || GL_VERSION_1_0)
    Texture1D = gl.Constants.GL_TEXTURE_1D, 
#endif

#if (GL_ARB_INTERNALFORMAT_QUERY2 || GL_VERSION_3_0)
    Texture1DArray = gl.Constants.GL_TEXTURE_1D_ARRAY, 
#endif

#if (GL_ARB_INTERNALFORMAT_QUERY2 || GL_VERSION_3_1)
    TextureRectangle = gl.Constants.GL_TEXTURE_RECTANGLE, 
#endif

}

#endif
