#if (GL_ANGLE_DEPTH_TEXTURE || GL_ES_VERSION_2_0 || GL_OES_DEPTH_TEXTURE || GL_VERSION_1_0 || GL_ARB_TEXTURE_STENCIL8 || GL_ES_VERSION_3_1 || GL_ES_VERSION_3_2 || GL_VERSION_4_4)

public enum DepthStencilTextureMode : GLenum { 
#if (GL_ANGLE_DEPTH_TEXTURE || GL_ES_VERSION_2_0 || GL_OES_DEPTH_TEXTURE || GL_VERSION_1_0)
    Component = gl.Constants.GL_DEPTH_COMPONENT, 
#endif

#if (GL_ARB_TEXTURE_STENCIL8 || GL_ES_VERSION_3_1 || GL_ES_VERSION_3_2 || GL_VERSION_1_0 || GL_VERSION_4_4)
    StencilIndex = gl.Constants.GL_STENCIL_INDEX, 
#endif

}

#endif
