#if (GL_QCOM_FRAMEBUFFER_FOVEATED || GL_QCOM_TEXTURE_FOVEATED || GL_QCOM_MOTION_ESTIMATION || GL_QCOM_TEXTURE_FOVEATED_SUBSAMPLED_LAYOUT)

public enum FoveationConfigBitQCOM : GLenum { 
#if (GL_QCOM_FRAMEBUFFER_FOVEATED || GL_QCOM_TEXTURE_FOVEATED)
    FoveationEnableBitQcom = gl.Constants.GL_FOVEATION_ENABLE_BIT_QCOM, 
#endif

#if (GL_QCOM_FRAMEBUFFER_FOVEATED || GL_QCOM_MOTION_ESTIMATION || GL_QCOM_TEXTURE_FOVEATED)
    ScaledBinMethodBitQcom = gl.Constants.GL_FOVEATION_SCALED_BIN_METHOD_BIT_QCOM, 
#endif

#if GL_QCOM_TEXTURE_FOVEATED_SUBSAMPLED_LAYOUT
    SubsampledLayoutMethodBitQcom = gl.Constants.GL_FOVEATION_SUBSAMPLED_LAYOUT_METHOD_BIT_QCOM, 
#endif

}

#endif
