#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_3_0 || GL_ES_VERSION_3_0 || GL_ARB_GEOMETRY_SHADER4 || GL_ES_VERSION_3_2 || GL_VERSION_3_2 || GL_EXT_COLOR_BUFFER_HALF_FLOAT || GL_EXT_FRAMEBUFFER_OBJECT || GL_EXT_GEOMETRY_SHADER || GL_EXT_GEOMETRY_SHADER4 || GL_NV_GEOMETRY_PROGRAM4 || GL_EXT_TEXTURE_ARRAY || GL_EXT_MULTISAMPLED_RENDER_TO_TEXTURE || GL_EXT_SRGB || GL_IMG_FRAMEBUFFER_DOWNSAMPLE || GL_OES_FRAMEBUFFER_OBJECT || GL_OES_GEOMETRY_SHADER || GL_OES_TEXTURE_3D || GL_OVR_MULTIVIEW)

public enum FramebufferAttachmentParameterName : GLenum { 
#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_3_0)
    ObjectType = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE, 
#endif

#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_3_0)
    ObjectName = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME, 
#endif

#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_3_0)
    TextureLevel = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL, 
#endif

#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ES_VERSION_2_0 || GL_VERSION_3_0)
    TextureCubeMapFace = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE, 
#endif

#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ES_VERSION_3_0 || GL_VERSION_3_0)
    ColorEncoding = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING, 
#endif

#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ES_VERSION_3_0 || GL_VERSION_3_0)
    ComponentType = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE, 
#endif

#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ES_VERSION_3_0 || GL_VERSION_3_0)
    RedSize = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE, 
#endif

#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ES_VERSION_3_0 || GL_VERSION_3_0)
    GreenSize = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE, 
#endif

#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ES_VERSION_3_0 || GL_VERSION_3_0)
    BlueSize = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE, 
#endif

#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ES_VERSION_3_0 || GL_VERSION_3_0)
    AlphaSize = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE, 
#endif

#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ES_VERSION_3_0 || GL_VERSION_3_0)
    DepthSize = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE, 
#endif

#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ES_VERSION_3_0 || GL_VERSION_3_0)
    StencilSize = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE, 
#endif

#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ARB_GEOMETRY_SHADER4 || GL_ES_VERSION_3_0 || GL_VERSION_3_0)
    TextureLayer = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER, 
#endif

#if (GL_ES_VERSION_3_2 || GL_VERSION_3_2)
    Layered = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_LAYERED, 
#endif

#if GL_ARB_GEOMETRY_SHADER4
    LayeredArb = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_LAYERED_ARB, 
#endif

#if GL_EXT_COLOR_BUFFER_HALF_FLOAT
    ComponentTypeExt = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE_EXT, 
#endif

#if GL_EXT_FRAMEBUFFER_OBJECT
    ObjectTypeExt = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE_EXT, 
#endif

#if GL_EXT_FRAMEBUFFER_OBJECT
    ObjectNameExt = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME_EXT, 
#endif

#if GL_EXT_FRAMEBUFFER_OBJECT
    TextureLevelExt = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL_EXT, 
#endif

#if GL_EXT_FRAMEBUFFER_OBJECT
    TextureCubeMapFaceExt = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE_EXT, 
#endif

#if GL_EXT_FRAMEBUFFER_OBJECT
    Texture3DZoffsetExt = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_3D_ZOFFSET_EXT, 
#endif

#if (GL_EXT_GEOMETRY_SHADER || GL_EXT_GEOMETRY_SHADER4 || GL_NV_GEOMETRY_PROGRAM4)
    LayeredExt = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_LAYERED_EXT, 
#endif

#if (GL_EXT_GEOMETRY_SHADER4 || GL_EXT_TEXTURE_ARRAY || GL_NV_GEOMETRY_PROGRAM4)
    TextureLayerExt = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER_EXT, 
#endif

#if GL_EXT_MULTISAMPLED_RENDER_TO_TEXTURE
    TextureSamplesExt = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_SAMPLES_EXT, 
#endif

#if GL_EXT_SRGB
    ColorEncodingExt = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING_EXT, 
#endif

#if GL_IMG_FRAMEBUFFER_DOWNSAMPLE
    TextureScaleImg = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_SCALE_IMG, 
#endif

#if GL_OES_FRAMEBUFFER_OBJECT
    ObjectTypeOes = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE_OES, 
#endif

#if GL_OES_FRAMEBUFFER_OBJECT
    ObjectNameOes = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME_OES, 
#endif

#if GL_OES_FRAMEBUFFER_OBJECT
    TextureLevelOes = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL_OES, 
#endif

#if GL_OES_FRAMEBUFFER_OBJECT
    TextureCubeMapFaceOes = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE_OES, 
#endif

#if GL_OES_GEOMETRY_SHADER
    LayeredOes = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_LAYERED_OES, 
#endif

#if GL_OES_TEXTURE_3D
    Texture3DZoffsetOes = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_3D_ZOFFSET_OES, 
#endif

#if GL_OVR_MULTIVIEW
    TextureNumViewsOvr = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_NUM_VIEWS_OVR, 
#endif

#if GL_OVR_MULTIVIEW
    TextureBaseViewIndexOvr = gl.Constants.GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_BASE_VIEW_INDEX_OVR, 
#endif

}

#endif
