#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_3_0 || GL_ES_VERSION_3_0 || GL_ES_VERSION_3_2 || GL_VERSION_3_2)

public enum FramebufferStatus : GLenum { 
#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_3_0)
    Complete = gl.Constants.GL_FRAMEBUFFER_COMPLETE, 
#endif

#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_3_0)
    IncompleteAttachment = gl.Constants.GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT, 
#endif

#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_3_0)
    IncompleteMissingAttachment = gl.Constants.GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT, 
#endif

#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_3_0)
    Unsupported = gl.Constants.GL_FRAMEBUFFER_UNSUPPORTED, 
#endif

#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ES_VERSION_3_0 || GL_SC_VERSION_2_0 || GL_VERSION_3_0)
    Undefined = gl.Constants.GL_FRAMEBUFFER_UNDEFINED, 
#endif

#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ES_VERSION_3_0 || GL_VERSION_3_0)
    IncompleteMultisample = gl.Constants.GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE, 
#endif

#if (GL_ES_VERSION_3_2 || GL_VERSION_3_2)
    IncompleteLayerTargets = gl.Constants.GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS, 
#endif

#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_VERSION_3_0)
    IncompleteDrawBuffer = gl.Constants.GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER, 
#endif

#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_VERSION_3_0)
    IncompleteReadBuffer = gl.Constants.GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER, 
#endif

}

#endif
