#if (GL_ARB_FRAMEBUFFER_NO_ATTACHMENTS || GL_ES_VERSION_3_1 || GL_VERSION_4_3 || GL_ES_VERSION_3_2)

public enum FramebufferParameterName : GLenum { 
#if (GL_ARB_FRAMEBUFFER_NO_ATTACHMENTS || GL_ES_VERSION_3_1 || GL_VERSION_4_3)
    DefaultWidth = gl.Constants.GL_FRAMEBUFFER_DEFAULT_WIDTH, 
#endif

#if (GL_ARB_FRAMEBUFFER_NO_ATTACHMENTS || GL_ES_VERSION_3_1 || GL_VERSION_4_3)
    DefaultHeight = gl.Constants.GL_FRAMEBUFFER_DEFAULT_HEIGHT, 
#endif

#if (GL_ARB_FRAMEBUFFER_NO_ATTACHMENTS || GL_ES_VERSION_3_1 || GL_VERSION_4_3)
    DefaultSamples = gl.Constants.GL_FRAMEBUFFER_DEFAULT_SAMPLES, 
#endif

#if (GL_ARB_FRAMEBUFFER_NO_ATTACHMENTS || GL_ES_VERSION_3_1 || GL_VERSION_4_3)
    DefaultFixedSampleLocations = gl.Constants.GL_FRAMEBUFFER_DEFAULT_FIXED_SAMPLE_LOCATIONS, 
#endif

#if (GL_ARB_FRAMEBUFFER_NO_ATTACHMENTS || GL_ES_VERSION_3_2 || GL_VERSION_4_3)
    DefaultLayers = gl.Constants.GL_FRAMEBUFFER_DEFAULT_LAYERS, 
#endif

}

#endif
