#if (GL_ARB_TESSELLATION_SHADER || GL_ES_VERSION_2_0 || GL_ES_VERSION_3_2 || GL_EXT_TESSELLATION_SHADER || GL_OES_TESSELLATION_SHADER || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0)

public enum FrontFaceDirection : GLenum { 
#if (GL_ARB_TESSELLATION_SHADER || GL_ES_VERSION_2_0 || GL_ES_VERSION_3_2 || GL_EXT_TESSELLATION_SHADER || GL_OES_TESSELLATION_SHADER || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0)
    Cw = gl.Constants.GL_CW, 
#endif

#if (GL_ARB_TESSELLATION_SHADER || GL_ES_VERSION_2_0 || GL_ES_VERSION_3_2 || GL_EXT_TESSELLATION_SHADER || GL_OES_TESSELLATION_SHADER || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0)
    Ccw = gl.Constants.GL_CCW, 
#endif

}

#endif
