#if (GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_1_3 || GL_VERSION_ES_CM_1_0 || GL_ARB_INTERNALFORMAT_QUERY2 || GL_ARB_ES2_COMPATIBILITY || GL_VERSION_4_1 || GL_ARB_FRAMEBUFFER_NO_ATTACHMENTS || GL_ES_VERSION_3_1 || GL_VERSION_4_3 || GL_ES_VERSION_3_2 || GL_VERSION_1_0)

public enum GetFramebufferParameter : GLenum { 
#if (GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_1_3 || GL_VERSION_ES_CM_1_0)
    SampleBuffers = gl.Constants.GL_SAMPLE_BUFFERS, 
#endif

#if (GL_ARB_INTERNALFORMAT_QUERY2 || GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_1_3 || GL_VERSION_ES_CM_1_0)
    Samples = gl.Constants.GL_SAMPLES, 
#endif

#if (GL_ARB_ES2_COMPATIBILITY || GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_4_1)
    ImplementationColorReadType = gl.Constants.GL_IMPLEMENTATION_COLOR_READ_TYPE, 
#endif

#if (GL_ARB_ES2_COMPATIBILITY || GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_4_1)
    ImplementationColorReadFormat = gl.Constants.GL_IMPLEMENTATION_COLOR_READ_FORMAT, 
#endif

#if (GL_ARB_FRAMEBUFFER_NO_ATTACHMENTS || GL_ES_VERSION_3_1 || GL_VERSION_4_3)
    FramebufferDefaultWidth = gl.Constants.GL_FRAMEBUFFER_DEFAULT_WIDTH, 
#endif

#if (GL_ARB_FRAMEBUFFER_NO_ATTACHMENTS || GL_ES_VERSION_3_1 || GL_VERSION_4_3)
    FramebufferDefaultHeight = gl.Constants.GL_FRAMEBUFFER_DEFAULT_HEIGHT, 
#endif

#if (GL_ARB_FRAMEBUFFER_NO_ATTACHMENTS || GL_ES_VERSION_3_1 || GL_VERSION_4_3)
    FramebufferDefaultSamples = gl.Constants.GL_FRAMEBUFFER_DEFAULT_SAMPLES, 
#endif

#if (GL_ARB_FRAMEBUFFER_NO_ATTACHMENTS || GL_ES_VERSION_3_1 || GL_VERSION_4_3)
    FramebufferDefaultFixedSampleLocations = gl.Constants.GL_FRAMEBUFFER_DEFAULT_FIXED_SAMPLE_LOCATIONS, 
#endif

#if (GL_ARB_FRAMEBUFFER_NO_ATTACHMENTS || GL_ES_VERSION_3_2 || GL_VERSION_4_3)
    FramebufferDefaultLayers = gl.Constants.GL_FRAMEBUFFER_DEFAULT_LAYERS, 
#endif

#if GL_VERSION_1_0
    Doublebuffer = gl.Constants.GL_DOUBLEBUFFER, 
#endif

#if GL_VERSION_1_0
    Stereo = gl.Constants.GL_STEREO, 
#endif

}

#endif
