#if (GL_ES_VERSION_2_0 || GL_EXT_RENDER_SNORM || GL_OES_BYTE_COORDINATES || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0 || GL_ANGLE_DEPTH_TEXTURE || GL_OES_DEPTH_TEXTURE || GL_OES_ELEMENT_INDEX_UINT || GL_ARB_VERTEX_SHADER || GL_OES_TEXTURE_FLOAT)

public enum ListNameType : GLenum { 
#if (GL_ES_VERSION_2_0 || GL_EXT_RENDER_SNORM || GL_OES_BYTE_COORDINATES || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0)
    Byte = gl.Constants.GL_BYTE, 
#endif

#if (GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0)
    UnsignedByte = gl.Constants.GL_UNSIGNED_BYTE, 
#endif

#if (GL_ES_VERSION_2_0 || GL_EXT_RENDER_SNORM || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0)
    Short = gl.Constants.GL_SHORT, 
#endif

#if (GL_ANGLE_DEPTH_TEXTURE || GL_ES_VERSION_2_0 || GL_OES_DEPTH_TEXTURE || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0)
    UnsignedShort = gl.Constants.GL_UNSIGNED_SHORT, 
#endif

#if (GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_1_0)
    Int = gl.Constants.GL_INT, 
#endif

#if (GL_ANGLE_DEPTH_TEXTURE || GL_ES_VERSION_2_0 || GL_OES_DEPTH_TEXTURE || GL_OES_ELEMENT_INDEX_UINT || GL_SC_VERSION_2_0 || GL_VERSION_1_0)
    UnsignedInt = gl.Constants.GL_UNSIGNED_INT, 
#endif

#if (GL_ARB_VERTEX_SHADER || GL_ES_VERSION_2_0 || GL_OES_TEXTURE_FLOAT || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0)
    Float = gl.Constants.GL_FLOAT, 
#endif

#if GL_VERSION_1_0
    _2Bytes = gl.Constants.GL_2_BYTES, 
#endif

#if GL_VERSION_1_0
    _3Bytes = gl.Constants.GL_3_BYTES, 
#endif

#if GL_VERSION_1_0
    _4Bytes = gl.Constants.GL_4_BYTES, 
#endif

}

#endif
