#if (GL_ARB_GET_PROGRAM_BINARY || GL_ES_VERSION_3_0 || GL_VERSION_4_1 || GL_ARB_SEPARATE_SHADER_OBJECTS || GL_ES_VERSION_3_1)

public enum ProgramParameterPName : GLenum { 
#if (GL_ARB_GET_PROGRAM_BINARY || GL_ES_VERSION_3_0 || GL_VERSION_4_1)
    BinaryRetrievableHint = gl.Constants.GL_PROGRAM_BINARY_RETRIEVABLE_HINT, 
#endif

#if (GL_ARB_SEPARATE_SHADER_OBJECTS || GL_ES_VERSION_3_1 || GL_VERSION_4_1)
    Separable = gl.Constants.GL_PROGRAM_SEPARABLE, 
#endif

}

#endif
