#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ARB_INTERNALFORMAT_QUERY2 || GL_ES_VERSION_2_0 || GL_NV_INTERNALFORMAT_SAMPLE_QUERY || GL_SC_VERSION_2_0 || GL_VERSION_3_0 || GL_OES_FRAMEBUFFER_OBJECT)

public enum RenderbufferTarget : GLenum { 
#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ARB_INTERNALFORMAT_QUERY2 || GL_ES_VERSION_2_0 || GL_NV_INTERNALFORMAT_SAMPLE_QUERY || GL_SC_VERSION_2_0 || GL_VERSION_3_0)
    Renderbuffer = gl.Constants.GL_RENDERBUFFER, 
#endif

#if GL_OES_FRAMEBUFFER_OBJECT
    Oes = gl.Constants.GL_RENDERBUFFER_OES, 
#endif

}

#endif
