#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_3_0 || GL_ES_VERSION_3_0 || GL_AMD_FRAMEBUFFER_MULTISAMPLE_ADVANCED || GL_ANGLE_FRAMEBUFFER_MULTISAMPLE || GL_APPLE_FRAMEBUFFER_MULTISAMPLE || GL_EXT_FRAMEBUFFER_MULTISAMPLE || GL_EXT_MULTISAMPLED_RENDER_TO_TEXTURE || GL_EXT_FRAMEBUFFER_OBJECT || GL_IMG_MULTISAMPLED_RENDER_TO_TEXTURE || GL_NV_FRAMEBUFFER_MULTISAMPLE || GL_NV_FRAMEBUFFER_MULTISAMPLE_COVERAGE || GL_OES_FRAMEBUFFER_OBJECT)

public enum RenderbufferParameterName : GLenum { 
#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_3_0)
    Width = gl.Constants.GL_RENDERBUFFER_WIDTH, 
#endif

#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_3_0)
    Height = gl.Constants.GL_RENDERBUFFER_HEIGHT, 
#endif

#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_3_0)
    InternalFormat = gl.Constants.GL_RENDERBUFFER_INTERNAL_FORMAT, 
#endif

#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_3_0)
    RedSize = gl.Constants.GL_RENDERBUFFER_RED_SIZE, 
#endif

#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_3_0)
    GreenSize = gl.Constants.GL_RENDERBUFFER_GREEN_SIZE, 
#endif

#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_3_0)
    BlueSize = gl.Constants.GL_RENDERBUFFER_BLUE_SIZE, 
#endif

#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_3_0)
    AlphaSize = gl.Constants.GL_RENDERBUFFER_ALPHA_SIZE, 
#endif

#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_3_0)
    DepthSize = gl.Constants.GL_RENDERBUFFER_DEPTH_SIZE, 
#endif

#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_3_0)
    StencilSize = gl.Constants.GL_RENDERBUFFER_STENCIL_SIZE, 
#endif

#if (GL_ARB_FRAMEBUFFER_OBJECT || GL_ES_VERSION_3_0 || GL_VERSION_3_0)
    Samples = gl.Constants.GL_RENDERBUFFER_SAMPLES, 
#endif

#if GL_AMD_FRAMEBUFFER_MULTISAMPLE_ADVANCED
    StorageSamplesAmd = gl.Constants.GL_RENDERBUFFER_STORAGE_SAMPLES_AMD, 
#endif

#if GL_ANGLE_FRAMEBUFFER_MULTISAMPLE
    SamplesAngle = gl.Constants.GL_RENDERBUFFER_SAMPLES_ANGLE, 
#endif

#if GL_APPLE_FRAMEBUFFER_MULTISAMPLE
    SamplesApple = gl.Constants.GL_RENDERBUFFER_SAMPLES_APPLE, 
#endif

#if (GL_EXT_FRAMEBUFFER_MULTISAMPLE || GL_EXT_MULTISAMPLED_RENDER_TO_TEXTURE)
    SamplesExt = gl.Constants.GL_RENDERBUFFER_SAMPLES_EXT, 
#endif

#if GL_EXT_FRAMEBUFFER_OBJECT
    WidthExt = gl.Constants.GL_RENDERBUFFER_WIDTH_EXT, 
#endif

#if GL_EXT_FRAMEBUFFER_OBJECT
    HeightExt = gl.Constants.GL_RENDERBUFFER_HEIGHT_EXT, 
#endif

#if GL_EXT_FRAMEBUFFER_OBJECT
    InternalFormatExt = gl.Constants.GL_RENDERBUFFER_INTERNAL_FORMAT_EXT, 
#endif

#if GL_EXT_FRAMEBUFFER_OBJECT
    RedSizeExt = gl.Constants.GL_RENDERBUFFER_RED_SIZE_EXT, 
#endif

#if GL_EXT_FRAMEBUFFER_OBJECT
    GreenSizeExt = gl.Constants.GL_RENDERBUFFER_GREEN_SIZE_EXT, 
#endif

#if GL_EXT_FRAMEBUFFER_OBJECT
    BlueSizeExt = gl.Constants.GL_RENDERBUFFER_BLUE_SIZE_EXT, 
#endif

#if GL_EXT_FRAMEBUFFER_OBJECT
    AlphaSizeExt = gl.Constants.GL_RENDERBUFFER_ALPHA_SIZE_EXT, 
#endif

#if GL_EXT_FRAMEBUFFER_OBJECT
    DepthSizeExt = gl.Constants.GL_RENDERBUFFER_DEPTH_SIZE_EXT, 
#endif

#if GL_EXT_FRAMEBUFFER_OBJECT
    StencilSizeExt = gl.Constants.GL_RENDERBUFFER_STENCIL_SIZE_EXT, 
#endif

#if GL_IMG_MULTISAMPLED_RENDER_TO_TEXTURE
    SamplesImg = gl.Constants.GL_RENDERBUFFER_SAMPLES_IMG, 
#endif

#if GL_NV_FRAMEBUFFER_MULTISAMPLE
    SamplesNv = gl.Constants.GL_RENDERBUFFER_SAMPLES_NV, 
#endif

#if GL_NV_FRAMEBUFFER_MULTISAMPLE_COVERAGE
    CoverageSamplesNv = gl.Constants.GL_RENDERBUFFER_COVERAGE_SAMPLES_NV, 
#endif

#if GL_NV_FRAMEBUFFER_MULTISAMPLE_COVERAGE
    ColorSamplesNv = gl.Constants.GL_RENDERBUFFER_COLOR_SAMPLES_NV, 
#endif

#if GL_OES_FRAMEBUFFER_OBJECT
    WidthOes = gl.Constants.GL_RENDERBUFFER_WIDTH_OES, 
#endif

#if GL_OES_FRAMEBUFFER_OBJECT
    HeightOes = gl.Constants.GL_RENDERBUFFER_HEIGHT_OES, 
#endif

#if GL_OES_FRAMEBUFFER_OBJECT
    InternalFormatOes = gl.Constants.GL_RENDERBUFFER_INTERNAL_FORMAT_OES, 
#endif

#if GL_OES_FRAMEBUFFER_OBJECT
    RedSizeOes = gl.Constants.GL_RENDERBUFFER_RED_SIZE_OES, 
#endif

#if GL_OES_FRAMEBUFFER_OBJECT
    GreenSizeOes = gl.Constants.GL_RENDERBUFFER_GREEN_SIZE_OES, 
#endif

#if GL_OES_FRAMEBUFFER_OBJECT
    BlueSizeOes = gl.Constants.GL_RENDERBUFFER_BLUE_SIZE_OES, 
#endif

#if GL_OES_FRAMEBUFFER_OBJECT
    AlphaSizeOes = gl.Constants.GL_RENDERBUFFER_ALPHA_SIZE_OES, 
#endif

#if GL_OES_FRAMEBUFFER_OBJECT
    DepthSizeOes = gl.Constants.GL_RENDERBUFFER_DEPTH_SIZE_OES, 
#endif

#if GL_OES_FRAMEBUFFER_OBJECT
    StencilSizeOes = gl.Constants.GL_RENDERBUFFER_STENCIL_SIZE_OES, 
#endif

}

#endif
