// #if (GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0 || GL_ARB_ROBUSTNESS || GL_ES_VERSION_3_2 || GL_EXT_ROBUSTNESS || GL_KHR_ROBUSTNESS || GL_VERSION_4_5 || GL_EXT_DRAW_BUFFERS_INDEXED || GL_NV_BLEND_EQUATION_ADVANCED || GL_NV_REGISTER_COMBINERS || GL_OES_DRAW_BUFFERS_INDEXED || GL_KHR_CONTEXT_FLUSH_CONTROL || GL_VERSION_4_6 || GL_ARB_UNIFORM_BUFFER_OBJECT || GL_ES_VERSION_3_0 || GL_VERSION_3_1 || GL_ARB_SYNC || GL_VERSION_3_2 || GL_AMD_FRAMEBUFFER_SAMPLE_POSITIONS || GL_APPLE_SYNC || GL_EXT_MEMORY_OBJECT || GL_EXT_SEMAPHORE || GL_EXT_MEMORY_OBJECT_WIN32 || GL_EXT_SEMAPHORE_WIN32 || GL_OES_FRAMEBUFFER_OBJECT)

// public enum SpecialNumbers : GLenum { 
// #if (GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0)
//     False = gl.Constants.GL_FALSE, 
// #endif

// #if (GL_ARB_ROBUSTNESS || GL_ES_VERSION_2_0 || GL_ES_VERSION_3_2 || GL_EXT_ROBUSTNESS || GL_KHR_ROBUSTNESS || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_4_5 || GL_VERSION_ES_CM_1_0)
//     NoError = gl.Constants.GL_NO_ERROR, 
// #endif

// #if (GL_ES_VERSION_2_0 || GL_EXT_DRAW_BUFFERS_INDEXED || GL_NV_BLEND_EQUATION_ADVANCED || GL_NV_REGISTER_COMBINERS || GL_OES_DRAW_BUFFERS_INDEXED || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0)
//     Zero = gl.Constants.GL_ZERO, 
// #endif

// #if (GL_ES_VERSION_2_0 || GL_KHR_CONTEXT_FLUSH_CONTROL || GL_NV_REGISTER_COMBINERS || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_4_5 || GL_VERSION_4_6)
//     None = gl.Constants.GL_NONE, 
// #endif

// #if (GL_ES_VERSION_2_0 || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0)
//     True = gl.Constants.GL_TRUE, 
// #endif

// #if (GL_ES_VERSION_2_0 || GL_EXT_DRAW_BUFFERS_INDEXED || GL_OES_DRAW_BUFFERS_INDEXED || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0)
//     One = gl.Constants.GL_ONE, 
// #endif

// #if (GL_ARB_UNIFORM_BUFFER_OBJECT || GL_ES_VERSION_3_0 || GL_VERSION_3_1)
//     InvalidIndex = gl.Constants.GL_INVALID_INDEX, 
// #endif

// #if (GL_ARB_SYNC || GL_ES_VERSION_3_0 || GL_VERSION_3_2)
//     TimeoutIgnored = gl.Constants.GL_TIMEOUT_IGNORED, 
// #endif

// #if GL_VERSION_ES_CM_1_0
//     VersionEsCl10 = gl.Constants.GL_VERSION_ES_CL_1_0, 
// #endif

// #if GL_VERSION_ES_CM_1_0
//     VersionEsCm11 = gl.Constants.GL_VERSION_ES_CM_1_1, 
// #endif

// #if GL_VERSION_ES_CM_1_0
//     VersionEsCl11 = gl.Constants.GL_VERSION_ES_CL_1_1, 
// #endif

// #if GL_AMD_FRAMEBUFFER_SAMPLE_POSITIONS
//     AllPixelsAmd = gl.Constants.GL_ALL_PIXELS_AMD, 
// #endif

// #if GL_APPLE_SYNC
//     TimeoutIgnoredApple = gl.Constants.GL_TIMEOUT_IGNORED_APPLE, 
// #endif

// #if (GL_EXT_MEMORY_OBJECT || GL_EXT_SEMAPHORE)
//     UuidSizeExt = gl.Constants.GL_UUID_SIZE_EXT, 
// #endif

// #if (GL_EXT_MEMORY_OBJECT_WIN32 || GL_EXT_SEMAPHORE_WIN32)
//     LuidSizeExt = gl.Constants.GL_LUID_SIZE_EXT, 
// #endif

// #if GL_OES_FRAMEBUFFER_OBJECT
//     NoneOes = gl.Constants.GL_NONE_OES, 
// #endif

// }

// #endif
