#if (GL_EXT_EGL_IMAGE_STORAGE_COMPRESSION || GL_EXT_TEXTURE_STORAGE_COMPRESSION)

public enum TexStorageAttribs : GLenum { 
#if (GL_EXT_EGL_IMAGE_STORAGE_COMPRESSION || GL_EXT_TEXTURE_STORAGE_COMPRESSION)
    SurfaceCompressionExt = gl.Constants.GL_SURFACE_COMPRESSION_EXT, 
#endif

#if (GL_EXT_EGL_IMAGE_STORAGE_COMPRESSION || GL_EXT_TEXTURE_STORAGE_COMPRESSION)
    SurfaceCompressionFixedRateDefaultExt = gl.Constants.GL_SURFACE_COMPRESSION_FIXED_RATE_DEFAULT_EXT, 
#endif

#if GL_EXT_TEXTURE_STORAGE_COMPRESSION
    SurfaceCompressionFixedRate1bpcExt = gl.Constants.GL_SURFACE_COMPRESSION_FIXED_RATE_1BPC_EXT, 
#endif

#if GL_EXT_TEXTURE_STORAGE_COMPRESSION
    SurfaceCompressionFixedRate2bpcExt = gl.Constants.GL_SURFACE_COMPRESSION_FIXED_RATE_2BPC_EXT, 
#endif

#if GL_EXT_TEXTURE_STORAGE_COMPRESSION
    SurfaceCompressionFixedRate3bpcExt = gl.Constants.GL_SURFACE_COMPRESSION_FIXED_RATE_3BPC_EXT, 
#endif

#if GL_EXT_TEXTURE_STORAGE_COMPRESSION
    SurfaceCompressionFixedRate4bpcExt = gl.Constants.GL_SURFACE_COMPRESSION_FIXED_RATE_4BPC_EXT, 
#endif

#if GL_EXT_TEXTURE_STORAGE_COMPRESSION
    SurfaceCompressionFixedRate5bpcExt = gl.Constants.GL_SURFACE_COMPRESSION_FIXED_RATE_5BPC_EXT, 
#endif

#if GL_EXT_TEXTURE_STORAGE_COMPRESSION
    SurfaceCompressionFixedRate6bpcExt = gl.Constants.GL_SURFACE_COMPRESSION_FIXED_RATE_6BPC_EXT, 
#endif

#if GL_EXT_TEXTURE_STORAGE_COMPRESSION
    SurfaceCompressionFixedRate7bpcExt = gl.Constants.GL_SURFACE_COMPRESSION_FIXED_RATE_7BPC_EXT, 
#endif

#if GL_EXT_TEXTURE_STORAGE_COMPRESSION
    SurfaceCompressionFixedRate8bpcExt = gl.Constants.GL_SURFACE_COMPRESSION_FIXED_RATE_8BPC_EXT, 
#endif

#if GL_EXT_TEXTURE_STORAGE_COMPRESSION
    SurfaceCompressionFixedRate9bpcExt = gl.Constants.GL_SURFACE_COMPRESSION_FIXED_RATE_9BPC_EXT, 
#endif

#if GL_EXT_TEXTURE_STORAGE_COMPRESSION
    SurfaceCompressionFixedRate10bpcExt = gl.Constants.GL_SURFACE_COMPRESSION_FIXED_RATE_10BPC_EXT, 
#endif

#if GL_EXT_TEXTURE_STORAGE_COMPRESSION
    SurfaceCompressionFixedRate11bpcExt = gl.Constants.GL_SURFACE_COMPRESSION_FIXED_RATE_11BPC_EXT, 
#endif

#if GL_EXT_TEXTURE_STORAGE_COMPRESSION
    SurfaceCompressionFixedRate12bpcExt = gl.Constants.GL_SURFACE_COMPRESSION_FIXED_RATE_12BPC_EXT, 
#endif

}

#endif
