#if (GL_ES_VERSION_2_0 || GL_KHR_CONTEXT_FLUSH_CONTROL || GL_NV_REGISTER_COMBINERS || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_4_5 || GL_VERSION_4_6 || GL_ES_VERSION_3_0 || GL_VERSION_3_0 || GL_VERSION_1_4)

public enum TextureCompareMode : GLenum { 
#if (GL_ES_VERSION_2_0 || GL_KHR_CONTEXT_FLUSH_CONTROL || GL_NV_REGISTER_COMBINERS || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_4_5 || GL_VERSION_4_6)
    None = gl.Constants.GL_NONE, 
#endif

#if (GL_ES_VERSION_3_0 || GL_VERSION_3_0)
    CompareRefToTexture = gl.Constants.GL_COMPARE_REF_TO_TEXTURE, 
#endif

#if GL_VERSION_1_4
    CompareRToTexture = gl.Constants.GL_COMPARE_R_TO_TEXTURE, 
#endif

}

#endif
