#if (GL_ES_VERSION_2_0 || GL_EXT_DRAW_BUFFERS_INDEXED || GL_NV_BLEND_EQUATION_ADVANCED || GL_NV_REGISTER_COMBINERS || GL_OES_DRAW_BUFFERS_INDEXED || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0 || GL_AMD_INTERLEAVED_ELEMENTS || GL_ES_VERSION_3_0)

public enum TextureSwizzle : GLenum { 
#if (GL_ES_VERSION_2_0 || GL_EXT_DRAW_BUFFERS_INDEXED || GL_NV_BLEND_EQUATION_ADVANCED || GL_NV_REGISTER_COMBINERS || GL_OES_DRAW_BUFFERS_INDEXED || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0)
    Zero = gl.Constants.GL_ZERO, 
#endif

#if (GL_ES_VERSION_2_0 || GL_EXT_DRAW_BUFFERS_INDEXED || GL_OES_DRAW_BUFFERS_INDEXED || GL_SC_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0)
    One = gl.Constants.GL_ONE, 
#endif

#if (GL_AMD_INTERLEAVED_ELEMENTS || GL_ES_VERSION_2_0 || GL_VERSION_1_0 || GL_VERSION_ES_CM_1_0)
    Alpha = gl.Constants.GL_ALPHA, 
#endif

#if (GL_AMD_INTERLEAVED_ELEMENTS || GL_ES_VERSION_3_0 || GL_SC_VERSION_2_0 || GL_VERSION_1_0)
    Red = gl.Constants.GL_RED, 
#endif

#if (GL_AMD_INTERLEAVED_ELEMENTS || GL_ES_VERSION_3_0 || GL_VERSION_1_0)
    Green = gl.Constants.GL_GREEN, 
#endif

#if (GL_AMD_INTERLEAVED_ELEMENTS || GL_ES_VERSION_3_0 || GL_VERSION_1_0)
    Blue = gl.Constants.GL_BLUE, 
#endif

}

#endif
