#if (GL_ARB_UNIFORM_BUFFER_OBJECT || GL_ES_VERSION_3_0 || GL_VERSION_3_1 || GL_ARB_SHADER_SUBROUTINE || GL_ARB_SHADER_ATOMIC_COUNTERS || GL_VERSION_4_2)

public enum UniformPName : GLenum { 
#if (GL_ARB_UNIFORM_BUFFER_OBJECT || GL_ES_VERSION_3_0 || GL_VERSION_3_1)
    Type = gl.Constants.GL_UNIFORM_TYPE, 
#endif

#if (GL_ARB_SHADER_SUBROUTINE || GL_ARB_UNIFORM_BUFFER_OBJECT || GL_ES_VERSION_3_0 || GL_VERSION_3_1)
    Size = gl.Constants.GL_UNIFORM_SIZE, 
#endif

#if (GL_ARB_SHADER_SUBROUTINE || GL_ARB_UNIFORM_BUFFER_OBJECT || GL_ES_VERSION_3_0 || GL_VERSION_3_1)
    NameLength = gl.Constants.GL_UNIFORM_NAME_LENGTH, 
#endif

#if (GL_ARB_UNIFORM_BUFFER_OBJECT || GL_ES_VERSION_3_0 || GL_VERSION_3_1)
    BlockIndex = gl.Constants.GL_UNIFORM_BLOCK_INDEX, 
#endif

#if (GL_ARB_UNIFORM_BUFFER_OBJECT || GL_ES_VERSION_3_0 || GL_VERSION_3_1)
    Offset = gl.Constants.GL_UNIFORM_OFFSET, 
#endif

#if (GL_ARB_UNIFORM_BUFFER_OBJECT || GL_ES_VERSION_3_0 || GL_VERSION_3_1)
    ArrayStride = gl.Constants.GL_UNIFORM_ARRAY_STRIDE, 
#endif

#if (GL_ARB_UNIFORM_BUFFER_OBJECT || GL_ES_VERSION_3_0 || GL_VERSION_3_1)
    MatrixStride = gl.Constants.GL_UNIFORM_MATRIX_STRIDE, 
#endif

#if (GL_ARB_UNIFORM_BUFFER_OBJECT || GL_ES_VERSION_3_0 || GL_VERSION_3_1)
    IsRowMajor = gl.Constants.GL_UNIFORM_IS_ROW_MAJOR, 
#endif

#if (GL_ARB_SHADER_ATOMIC_COUNTERS || GL_VERSION_4_2)
    AtomicCounterBufferIndex = gl.Constants.GL_UNIFORM_ATOMIC_COUNTER_BUFFER_INDEX, 
#endif

}

#endif
