#if (GL_ARB_UNIFORM_BUFFER_OBJECT || GL_ES_VERSION_3_0 || GL_VERSION_3_1 || GL_ARB_TESSELLATION_SHADER || GL_VERSION_4_0 || GL_ARB_COMPUTE_SHADER || GL_VERSION_4_3)

public enum UniformBlockPName : GLenum { 
#if (GL_ARB_UNIFORM_BUFFER_OBJECT || GL_ES_VERSION_3_0 || GL_VERSION_3_1)
    Binding = gl.Constants.GL_UNIFORM_BLOCK_BINDING, 
#endif

#if (GL_ARB_UNIFORM_BUFFER_OBJECT || GL_ES_VERSION_3_0 || GL_VERSION_3_1)
    DataSize = gl.Constants.GL_UNIFORM_BLOCK_DATA_SIZE, 
#endif

#if (GL_ARB_UNIFORM_BUFFER_OBJECT || GL_ES_VERSION_3_0 || GL_VERSION_3_1)
    NameLength = gl.Constants.GL_UNIFORM_BLOCK_NAME_LENGTH, 
#endif

#if (GL_ARB_UNIFORM_BUFFER_OBJECT || GL_ES_VERSION_3_0 || GL_VERSION_3_1)
    ActiveUniforms = gl.Constants.GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS, 
#endif

#if (GL_ARB_UNIFORM_BUFFER_OBJECT || GL_ES_VERSION_3_0 || GL_VERSION_3_1)
    ActiveUniformIndices = gl.Constants.GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES, 
#endif

#if (GL_ARB_UNIFORM_BUFFER_OBJECT || GL_ES_VERSION_3_0 || GL_VERSION_3_1)
    ReferencedByVertexShader = gl.Constants.GL_UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER, 
#endif

#if (GL_ARB_UNIFORM_BUFFER_OBJECT || GL_ES_VERSION_3_0 || GL_VERSION_3_1)
    ReferencedByFragmentShader = gl.Constants.GL_UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER, 
#endif

#if (GL_ARB_UNIFORM_BUFFER_OBJECT || GL_VERSION_3_1)
    ReferencedByGeometryShader = gl.Constants.GL_UNIFORM_BLOCK_REFERENCED_BY_GEOMETRY_SHADER, 
#endif

#if (GL_ARB_TESSELLATION_SHADER || GL_VERSION_4_0)
    ReferencedByTessControlShader = gl.Constants.GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_CONTROL_SHADER, 
#endif

#if (GL_ARB_TESSELLATION_SHADER || GL_VERSION_4_0)
    ReferencedByTessEvaluationShader = gl.Constants.GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_EVALUATION_SHADER, 
#endif

#if (GL_ARB_COMPUTE_SHADER || GL_VERSION_4_3)
    ReferencedByComputeShader = gl.Constants.GL_UNIFORM_BLOCK_REFERENCED_BY_COMPUTE_SHADER, 
#endif

}

#endif
