partial class hgl {
    // glAttachShader
    // glBindAttribLocation
    // glBindFragDataLocation
    // glBindFragDataLocationIndexed
    // glCompileShader
    // glCreateProgram
    // glCreateShader
    // glCreateShaderProgram
    // glDeleteProgram
    // glDeleteShader
    // glDetachShader
    // glGetActiveAtomicCounterBufferiv
    // glGetActiveAttrib
    // glGetActiveSubroutineName
    // glGetActiveSubroutineUniform
    // glGetActiveSubroutineUniformName
    // glGetActiveUniform
    // glGetActiveUniformBlock
    // glGetActiveUniformBlockName
    // glGetActiveUniformName
    // glGetActiveUniformsiv
    // glGetAttachedShaders
    // glGetAttribLocation
    // glGetFragDataIndex
    // glGetFragDataLocation
    // glGetProgram
    // glGetProgramBinary
    // glGetProgramInfoLog
    // glGetProgramResource
    // glGetProgramResourceIndex
    // glGetProgramResourceLocation
    // glGetProgramResourceLocationIndex
    // glGetProgramResourceName
    // glGetProgramStage
    // glGetShader
    // glGetShaderInfoLog
    // glGetShaderPrecisionFormat
    // glGetShaderSource
    // glGetSubroutineIndex
    // glGetSubroutineUniformLocation
    // glGetUniform
    // glGetUniformBlockIndex
    // glGetUniformIndices
    // glGetUniformLocation
    // glGetUniformSubroutine
    // glIsProgram
    // glIsShader
    // glLinkProgram
    // glMinSampleShading
    // glProgramBinary
    // glProgramParameter
    // glProgramUniform
    // glReleaseShaderCompiler
    // glShaderBinary
    // glShaderSource
    // glShaderStorageBlockBinding
    // glUniform
    // glUniformBlockBinding
    // glUniformSubroutines
    // glUseProgram
    // glUseProgramStages
    // glValidateProgram
}