partial class hgl {
    // glActiveTexture
    // glBindImageTexture
    // glBindImageTextures
    // glBindTexture
    // glBindTextureUnit
    // glBindTextures
    // glClearTexImage
    // glClearTexSubImage
    // glCompressedTexImage1D
    // glCompressedTexImage2D
    // glCompressedTexImage3D
    // glCompressedTexSubImage1D
    // glCompressedTexSubImage2D
    // glCompressedTexSubImage3D
    // glCopyImageSubData
    // glCopyTexImage1D
    // glCopyTexImage2D
    // glCopyTexSubImage1D
    // glCopyTexSubImage2D
    // glCopyTexSubImage3D
    // glCreateTextures
    // glDeleteTextures
    // glGenTextures
    // glGetCompressedTexImage
    // glGetCompressedTextureSubImage
    // glGetTexImage
    // glGetTexLevelParameter
    // glGetTexParameter
    // glGetTextureSubImage
    // glInvalidateTexImage
    // glInvalidateTexSubImage
    // glIsTexture
    // glTexBuffer
    // glTexBufferRange
    // glTexImage1D
    // glTexImage2D
    // glTexImage2DMultisample
    // glTexImage3D
    // glTexImage3DMultisample
    // glTexParameter
    // glTexStorage1D
    // glTexStorage2D
    // glTexStorage2DMultisample
    // glTexStorage3D
    // glTexStorage3DMultisample
    // glTexSubImage1D
    // glTexSubImage2D
    // glTexSubImage3D
    // glTextureView
}