public enum ProgramInterface : GLenum {
    TransformFeedbackBuffer = gl.Constants.GL_TRANSFORM_FEEDBACK_BUFFER,
    Uniform = gl.Constants.GL_UNIFORM,
    UniformBlock = gl.Constants.GL_UNIFORM_BLOCK,
    ProgramInput = gl.Constants.GL_PROGRAM_INPUT,
    ProgramOutput = gl.Constants.GL_PROGRAM_OUTPUT,
    BufferVariable = gl.Constants.GL_BUFFER_VARIABLE,
    ShaderStorageBlock = gl.Constants.GL_SHADER_STORAGE_BLOCK,
    VertexSubroutine = gl.Constants.GL_VERTEX_SUBROUTINE,
    TessControlSubroutine = gl.Constants.GL_TESS_CONTROL_SUBROUTINE,
    TessEvaluationSubroutine = gl.Constants.GL_TESS_EVALUATION_SUBROUTINE,
    GeometrySubroutine = gl.Constants.GL_GEOMETRY_SUBROUTINE,
    FragmentSubroutine = gl.Constants.GL_FRAGMENT_SUBROUTINE,
    ComputeSubroutine = gl.Constants.GL_COMPUTE_SUBROUTINE,
    VertexSubroutineUniform = gl.Constants.GL_VERTEX_SUBROUTINE_UNIFORM,
    TessControlSubroutineUniform = gl.Constants.GL_TESS_CONTROL_SUBROUTINE_UNIFORM,
    TessEvaluationSubroutineUniform = gl.Constants.GL_TESS_EVALUATION_SUBROUTINE_UNIFORM,
    GeometrySubroutineUniform = gl.Constants.GL_GEOMETRY_SUBROUTINE_UNIFORM,
    FragmentSubroutineUniform = gl.Constants.GL_FRAGMENT_SUBROUTINE_UNIFORM,
    ComputeSubroutineUniform = gl.Constants.GL_COMPUTE_SUBROUTINE_UNIFORM,
    TransformFeedbackVarying = gl.Constants.GL_TRANSFORM_FEEDBACK_VARYING,
}
