#if (GL_ARB_IMAGING || GL_ES_VERSION_2_0 || GL_EXT_DRAW_BUFFERS_INDEXED || GL_OES_DRAW_BUFFERS_INDEXED || GL_SC_VERSION_2_0 || GL_VERSION_1_4 || GL_ES_VERSION_3_0 || GL_EXT_BLEND_MINMAX || GL_EXT_BLEND_SUBTRACT || GL_SGIX_BLEND_ALPHA_MINMAX)

public enum BlendEquationModeEXT : GLenum { 
#if (GL_ARB_IMAGING || GL_ES_VERSION_2_0 || GL_EXT_DRAW_BUFFERS_INDEXED || GL_OES_DRAW_BUFFERS_INDEXED || GL_SC_VERSION_2_0 || GL_VERSION_1_4)
    FuncAdd = gl.Constants.GL_FUNC_ADD, 
#endif

#if (GL_ARB_IMAGING || GL_ES_VERSION_2_0 || GL_EXT_DRAW_BUFFERS_INDEXED || GL_OES_DRAW_BUFFERS_INDEXED || GL_SC_VERSION_2_0 || GL_VERSION_1_4)
    FuncSubtract = gl.Constants.GL_FUNC_SUBTRACT, 
#endif

#if (GL_ARB_IMAGING || GL_ES_VERSION_2_0 || GL_EXT_DRAW_BUFFERS_INDEXED || GL_OES_DRAW_BUFFERS_INDEXED || GL_SC_VERSION_2_0 || GL_VERSION_1_4)
    FuncReverseSubtract = gl.Constants.GL_FUNC_REVERSE_SUBTRACT, 
#endif

#if (GL_ARB_IMAGING || GL_ES_VERSION_3_0 || GL_EXT_DRAW_BUFFERS_INDEXED || GL_OES_DRAW_BUFFERS_INDEXED || GL_VERSION_1_4)
    Min = gl.Constants.GL_MIN, 
#endif

#if (GL_ARB_IMAGING || GL_ES_VERSION_3_0 || GL_EXT_DRAW_BUFFERS_INDEXED || GL_OES_DRAW_BUFFERS_INDEXED || GL_VERSION_1_4)
    Max = gl.Constants.GL_MAX, 
#endif

#if GL_EXT_BLEND_MINMAX
    FuncAddExt = gl.Constants.GL_FUNC_ADD_EXT, 
#endif

#if GL_EXT_BLEND_MINMAX
    MinExt = gl.Constants.GL_MIN_EXT, 
#endif

#if GL_EXT_BLEND_MINMAX
    MaxExt = gl.Constants.GL_MAX_EXT, 
#endif

#if GL_EXT_BLEND_SUBTRACT
    FuncSubtractExt = gl.Constants.GL_FUNC_SUBTRACT_EXT, 
#endif

#if GL_EXT_BLEND_SUBTRACT
    FuncReverseSubtractExt = gl.Constants.GL_FUNC_REVERSE_SUBTRACT_EXT, 
#endif

#if GL_SGIX_BLEND_ALPHA_MINMAX
    AlphaMinSgix = gl.Constants.GL_ALPHA_MIN_SGIX, 
#endif

#if GL_SGIX_BLEND_ALPHA_MINMAX
    AlphaMaxSgix = gl.Constants.GL_ALPHA_MAX_SGIX, 
#endif

}

#endif
