#if GL_EXT_direct_state_access

public partial class gl { 
    public partial class Functions { 
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, GLtexture, void> glBindMultiTextureEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, FramebufferTarget, FramebufferStatus> glCheckNamedFramebufferStatusEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLbuffer, SizedInternalFormat, PixelFormat, PixelType, void*, void> glClearNamedBufferDataEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLbuffer, SizedInternalFormat, GLsizeiptr, GLsizeiptr, PixelFormat, PixelType, void*, void> glClearNamedBufferSubDataEXT;
        public static unsafe delegate* unmanaged[Cdecl]<ClientAttribMask, void> glClientAttribDefaultEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, GLint, InternalFormat, GLsizei, GLint, GLsizei, void*, void> glCompressedMultiTexImage1DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, GLint, InternalFormat, GLsizei, GLsizei, GLint, GLsizei, void*, void> glCompressedMultiTexImage2DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, GLint, InternalFormat, GLsizei, GLsizei, GLsizei, GLint, GLsizei, void*, void> glCompressedMultiTexImage3DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, GLint, GLint, GLsizei, InternalFormat, GLsizei, void*, void> glCompressedMultiTexSubImage1DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, GLint, GLint, GLint, GLsizei, GLsizei, InternalFormat, GLsizei, void*, void> glCompressedMultiTexSubImage2DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, InternalFormat, GLsizei, void*, void> glCompressedMultiTexSubImage3DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, GLint, InternalFormat, GLsizei, GLint, GLsizei, void*, void> glCompressedTextureImage1DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, GLint, InternalFormat, GLsizei, GLsizei, GLint, GLsizei, void*, void> glCompressedTextureImage2DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, GLint, InternalFormat, GLsizei, GLsizei, GLsizei, GLint, GLsizei, void*, void> glCompressedTextureImage3DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, GLint, GLint, GLsizei, InternalFormat, GLsizei, void*, void> glCompressedTextureSubImage1DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, GLint, GLint, GLint, GLsizei, GLsizei, InternalFormat, GLsizei, void*, void> glCompressedTextureSubImage2DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, InternalFormat, GLsizei, void*, void> glCompressedTextureSubImage3DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, GLint, InternalFormat, GLint, GLint, GLsizei, GLint, void> glCopyMultiTexImage1DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, GLint, InternalFormat, GLint, GLint, GLsizei, GLsizei, GLint, void> glCopyMultiTexImage2DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, GLint, GLint, GLint, GLint, GLsizei, void> glCopyMultiTexSubImage1DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei, void> glCopyMultiTexSubImage2DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, GLint, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei, void> glCopyMultiTexSubImage3DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, GLint, InternalFormat, GLint, GLint, GLsizei, GLint, void> glCopyTextureImage1DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, GLint, InternalFormat, GLint, GLint, GLsizei, GLsizei, GLint, void> glCopyTextureImage2DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, GLint, GLint, GLint, GLint, GLsizei, void> glCopyTextureSubImage1DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei, void> glCopyTextureSubImage2DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, GLint, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei, void> glCopyTextureSubImage3DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLCapability, GLuint, void> glDisableClientStateiEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLCapability, GLuint, void> glDisableClientStateIndexedEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLCapability, GLuint, void> glDisableIndexedEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLuint, void> glDisableVertexArrayAttribEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLCapability, void> glDisableVertexArrayEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLCapability, GLuint, void> glEnableClientStateiEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLCapability, GLuint, void> glEnableClientStateIndexedEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLCapability, GLuint, void> glEnableIndexedEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLuint, void> glEnableVertexArrayAttribEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLCapability, void> glEnableVertexArrayEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLbuffer, GLintptr, GLsizeiptr, void> glFlushMappedNamedBufferRangeEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, ColorBuffer, void> glFramebufferDrawBufferEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, GLsizei, ColorBuffer*, void> glFramebufferDrawBuffersEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, ColorBuffer, void> glFramebufferReadBufferEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, void> glGenerateMultiTexMipmapEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, void> glGenerateTextureMipmapEXT;
        public static unsafe delegate* unmanaged[Cdecl]<BufferTarget, GLuint, GLboolean*, void> glGetBooleanIndexedvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, GLint, void*, void> glGetCompressedMultiTexImageEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, GLint, void*, void> glGetCompressedTextureImageEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLParameter, GLuint, GLdouble*, void> glGetDoublei_vEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLParameter, GLuint, GLdouble*, void> glGetDoubleIndexedvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLParameter, GLuint, GLfloat*, void> glGetFloati_vEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLParameter, GLuint, GLfloat*, void> glGetFloatIndexedvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, FramebufferParameter, GLint*, void> glGetFramebufferParameterivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLParameter, GLuint, GLint*, void> glGetIntegerIndexedvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureEnvTarget, TextureEnvParameter, GLfloat*, void> glGetMultiTexEnvfvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureEnvTarget, TextureEnvParameter, GLint*, void> glGetMultiTexEnvivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureCoordName, TextureGenParameter, GLdouble*, void> glGetMultiTexGendvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureCoordName, TextureGenParameter, GLfloat*, void> glGetMultiTexGenfvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureCoordName, TextureGenParameter, GLint*, void> glGetMultiTexGenivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, GLint, PixelFormat, PixelType, void*, void> glGetMultiTexImageEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, GLint, TextureParameter, GLfloat*, void> glGetMultiTexLevelParameterfvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, GLint, TextureParameter, GLint*, void> glGetMultiTexLevelParameterivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, TextureParameter, GLfloat*, void> glGetMultiTexParameterfvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, TextureParameter, GLint*, void> glGetMultiTexParameterIivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, TextureParameter, GLuint*, void> glGetMultiTexParameterIuivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, TextureParameter, GLint*, void> glGetMultiTexParameterivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLbuffer, BufferParameter, GLint*, void> glGetNamedBufferParameterivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLbuffer, BufferPointerParameter, void**, void> glGetNamedBufferPointervEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLbuffer, GLintptr, GLsizeiptr, void*, void> glGetNamedBufferSubDataEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, FramebufferAttachment, FramebufferAttachmentParameter, GLint*, void> glGetNamedFramebufferAttachmentParameterivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, FramebufferParameter, GLint*, void> glGetNamedFramebufferParameterivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, ProgramTarget, ProgramProperty, GLint*, void> glGetNamedProgramivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, ProgramTarget, GLuint, GLdouble*, void> glGetNamedProgramLocalParameterdvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, ProgramTarget, GLuint, GLfloat*, void> glGetNamedProgramLocalParameterfvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, ProgramTarget, GLuint, GLint*, void> glGetNamedProgramLocalParameterIivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, ProgramTarget, GLuint, GLuint*, void> glGetNamedProgramLocalParameterIuivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, ProgramTarget, ProgramStringProperty, void*, void> glGetNamedProgramStringEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLrenderbuffer, RenderbufferParameter, GLint*, void> glGetNamedRenderbufferParameterivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLenum, GLuint, void**, void> glGetPointeri_vEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLenum, GLuint, void**, void> glGetPointerIndexedvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, GLint, PixelFormat, PixelType, void*, void> glGetTextureImageEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, GLint, TextureParameter, GLfloat*, void> glGetTextureLevelParameterfvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, GLint, TextureParameter, GLint*, void> glGetTextureLevelParameterivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, TextureParameter, GLfloat*, void> glGetTextureParameterfvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, TextureParameter, GLint*, void> glGetTextureParameterIivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, TextureParameter, GLuint*, void> glGetTextureParameterIuivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, TextureParameter, GLint*, void> glGetTextureParameterivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLuint, VertexArrayParameter, GLint*, void> glGetVertexArrayIntegeri_vEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, VertexArrayParameter, GLint*, void> glGetVertexArrayIntegervEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLuint, VertexArrayParameter, void**, void> glGetVertexArrayPointeri_vEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, VertexArrayParameter, void**, void> glGetVertexArrayPointervEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLCapability, GLuint, GLboolean> glIsEnabledIndexedEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLbuffer, BufferAccess, void*> glMapNamedBufferEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLbuffer, GLintptr, GLsizeiptr, MapBufferAccessMask, void*> glMapNamedBufferRangeEXT;
        public static unsafe delegate* unmanaged[Cdecl]<MatrixMode, GLdouble, GLdouble, GLdouble, GLdouble, GLdouble, GLdouble, void> glMatrixFrustumEXT;
        public static unsafe delegate* unmanaged[Cdecl]<MatrixMode, GLdouble*, void> glMatrixLoaddEXT;
        public static unsafe delegate* unmanaged[Cdecl]<MatrixMode, GLfloat*, void> glMatrixLoadfEXT;
        public static unsafe delegate* unmanaged[Cdecl]<MatrixMode, void> glMatrixLoadIdentityEXT;
        public static unsafe delegate* unmanaged[Cdecl]<MatrixMode, GLdouble*, void> glMatrixLoadTransposedEXT;
        public static unsafe delegate* unmanaged[Cdecl]<MatrixMode, GLfloat*, void> glMatrixLoadTransposefEXT;
        public static unsafe delegate* unmanaged[Cdecl]<MatrixMode, GLdouble*, void> glMatrixMultdEXT;
        public static unsafe delegate* unmanaged[Cdecl]<MatrixMode, GLfloat*, void> glMatrixMultfEXT;
        public static unsafe delegate* unmanaged[Cdecl]<MatrixMode, GLdouble*, void> glMatrixMultTransposedEXT;
        public static unsafe delegate* unmanaged[Cdecl]<MatrixMode, GLfloat*, void> glMatrixMultTransposefEXT;
        public static unsafe delegate* unmanaged[Cdecl]<MatrixMode, GLdouble, GLdouble, GLdouble, GLdouble, GLdouble, GLdouble, void> glMatrixOrthoEXT;
        public static unsafe delegate* unmanaged[Cdecl]<MatrixMode, void> glMatrixPopEXT;
        public static unsafe delegate* unmanaged[Cdecl]<MatrixMode, void> glMatrixPushEXT;
        public static unsafe delegate* unmanaged[Cdecl]<MatrixMode, GLdouble, GLdouble, GLdouble, GLdouble, void> glMatrixRotatedEXT;
        public static unsafe delegate* unmanaged[Cdecl]<MatrixMode, GLfloat, GLfloat, GLfloat, GLfloat, void> glMatrixRotatefEXT;
        public static unsafe delegate* unmanaged[Cdecl]<MatrixMode, GLdouble, GLdouble, GLdouble, void> glMatrixScaledEXT;
        public static unsafe delegate* unmanaged[Cdecl]<MatrixMode, GLfloat, GLfloat, GLfloat, void> glMatrixScalefEXT;
        public static unsafe delegate* unmanaged[Cdecl]<MatrixMode, GLdouble, GLdouble, GLdouble, void> glMatrixTranslatedEXT;
        public static unsafe delegate* unmanaged[Cdecl]<MatrixMode, GLfloat, GLfloat, GLfloat, void> glMatrixTranslatefEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, InternalFormat, GLbuffer, void> glMultiTexBufferEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, GLint, TexCoordPointerType, GLsizei, void*, void> glMultiTexCoordPointerEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureEnvTarget, TextureEnvParameter, GLfloat, void> glMultiTexEnvfEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureEnvTarget, TextureEnvParameter, GLfloat*, void> glMultiTexEnvfvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureEnvTarget, TextureEnvParameter, GLint, void> glMultiTexEnviEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureEnvTarget, TextureEnvParameter, GLint*, void> glMultiTexEnvivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureCoordName, TextureGenParameter, GLdouble, void> glMultiTexGendEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureCoordName, TextureGenParameter, GLdouble*, void> glMultiTexGendvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureCoordName, TextureGenParameter, GLfloat, void> glMultiTexGenfEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureCoordName, TextureGenParameter, GLfloat*, void> glMultiTexGenfvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureCoordName, TextureGenParameter, GLint, void> glMultiTexGeniEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureCoordName, TextureGenParameter, GLint*, void> glMultiTexGenivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, GLint, InternalFormat, GLsizei, GLint, PixelFormat, PixelType, void*, void> glMultiTexImage1DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, GLint, InternalFormat, GLsizei, GLsizei, GLint, PixelFormat, PixelType, void*, void> glMultiTexImage2DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, GLint, InternalFormat, GLsizei, GLsizei, GLsizei, GLint, PixelFormat, PixelType, void*, void> glMultiTexImage3DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, TextureParameter, GLfloat, void> glMultiTexParameterfEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, TextureParameter, GLfloat*, void> glMultiTexParameterfvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, TextureParameter, GLint, void> glMultiTexParameteriEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, TextureParameter, GLint*, void> glMultiTexParameterIivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, TextureParameter, GLuint*, void> glMultiTexParameterIuivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, TextureParameter, GLint*, void> glMultiTexParameterivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, GLrenderbuffer, void> glMultiTexRenderbufferEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, GLint, GLint, GLsizei, PixelFormat, PixelType, void*, void> glMultiTexSubImage1DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, GLint, GLint, GLint, GLsizei, GLsizei, PixelFormat, PixelType, void*, void> glMultiTexSubImage2DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<TextureUnit, TextureTarget, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, PixelFormat, PixelType, void*, void> glMultiTexSubImage3DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLbuffer, GLsizeiptr, void*, BufferUsage, void> glNamedBufferDataEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLbuffer, GLsizeiptr, void*, BufferStorageMask, void> glNamedBufferStorageEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLbuffer, GLintptr, GLsizeiptr, void*, void> glNamedBufferSubDataEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLbuffer, GLbuffer, GLintptr, GLintptr, GLsizeiptr, void> glNamedCopyBufferSubDataEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, FramebufferParameter, GLint, void> glNamedFramebufferParameteriEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, FramebufferAttachment, RenderbufferTarget, GLrenderbuffer, void> glNamedFramebufferRenderbufferEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, FramebufferAttachment, TextureTarget, GLtexture, GLint, void> glNamedFramebufferTexture1DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, FramebufferAttachment, TextureTarget, GLtexture, GLint, void> glNamedFramebufferTexture2DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, FramebufferAttachment, TextureTarget, GLtexture, GLint, GLint, void> glNamedFramebufferTexture3DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, FramebufferAttachment, GLtexture, GLint, void> glNamedFramebufferTextureEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, FramebufferAttachment, GLtexture, GLint, TextureTarget, void> glNamedFramebufferTextureFaceEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, FramebufferAttachment, GLtexture, GLint, GLint, void> glNamedFramebufferTextureLayerEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, ProgramTarget, GLuint, GLdouble, GLdouble, GLdouble, GLdouble, void> glNamedProgramLocalParameter4dEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, ProgramTarget, GLuint, GLdouble*, void> glNamedProgramLocalParameter4dvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, ProgramTarget, GLuint, GLfloat, GLfloat, GLfloat, GLfloat, void> glNamedProgramLocalParameter4fEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, ProgramTarget, GLuint, GLfloat*, void> glNamedProgramLocalParameter4fvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, ProgramTarget, GLuint, GLint, GLint, GLint, GLint, void> glNamedProgramLocalParameterI4iEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, ProgramTarget, GLuint, GLint*, void> glNamedProgramLocalParameterI4ivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, ProgramTarget, GLuint, GLuint, GLuint, GLuint, GLuint, void> glNamedProgramLocalParameterI4uiEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, ProgramTarget, GLuint, GLuint*, void> glNamedProgramLocalParameterI4uivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, ProgramTarget, GLuint, GLsizei, GLfloat*, void> glNamedProgramLocalParameters4fvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, ProgramTarget, GLuint, GLsizei, GLint*, void> glNamedProgramLocalParametersI4ivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, ProgramTarget, GLuint, GLsizei, GLuint*, void> glNamedProgramLocalParametersI4uivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, ProgramTarget, ProgramFormat, GLsizei, void*, void> glNamedProgramStringEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLrenderbuffer, InternalFormat, GLsizei, GLsizei, void> glNamedRenderbufferStorageEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLrenderbuffer, GLsizei, GLsizei, InternalFormat, GLsizei, GLsizei, void> glNamedRenderbufferStorageMultisampleCoverageEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLrenderbuffer, GLsizei, InternalFormat, GLsizei, GLsizei, void> glNamedRenderbufferStorageMultisampleEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLdouble, void> glProgramUniform1dEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLdouble*, void> glProgramUniform1dvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLfloat, void> glProgramUniform1fEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLfloat*, void> glProgramUniform1fvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLint, void> glProgramUniform1iEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLint*, void> glProgramUniform1ivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLuint, void> glProgramUniform1uiEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLuint*, void> glProgramUniform1uivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLdouble, GLdouble, void> glProgramUniform2dEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLdouble*, void> glProgramUniform2dvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLfloat, GLfloat, void> glProgramUniform2fEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLfloat*, void> glProgramUniform2fvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLint, GLint, void> glProgramUniform2iEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLint*, void> glProgramUniform2ivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLuint, GLuint, void> glProgramUniform2uiEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLuint*, void> glProgramUniform2uivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLdouble, GLdouble, GLdouble, void> glProgramUniform3dEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLdouble*, void> glProgramUniform3dvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLfloat, GLfloat, GLfloat, void> glProgramUniform3fEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLfloat*, void> glProgramUniform3fvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLint, GLint, GLint, void> glProgramUniform3iEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLint*, void> glProgramUniform3ivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLuint, GLuint, GLuint, void> glProgramUniform3uiEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLuint*, void> glProgramUniform3uivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLdouble, GLdouble, GLdouble, GLdouble, void> glProgramUniform4dEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLdouble*, void> glProgramUniform4dvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLfloat, GLfloat, GLfloat, GLfloat, void> glProgramUniform4fEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLfloat*, void> glProgramUniform4fvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLint, GLint, GLint, GLint, void> glProgramUniform4iEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLint*, void> glProgramUniform4ivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLuint, GLuint, GLuint, GLuint, void> glProgramUniform4uiEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLuint*, void> glProgramUniform4uivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLboolean, GLdouble*, void> glProgramUniformMatrix2dvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLboolean, GLfloat*, void> glProgramUniformMatrix2fvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLboolean, GLdouble*, void> glProgramUniformMatrix2x3dvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLboolean, GLfloat*, void> glProgramUniformMatrix2x3fvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLboolean, GLdouble*, void> glProgramUniformMatrix2x4dvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLboolean, GLfloat*, void> glProgramUniformMatrix2x4fvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLboolean, GLdouble*, void> glProgramUniformMatrix3dvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLboolean, GLfloat*, void> glProgramUniformMatrix3fvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLboolean, GLdouble*, void> glProgramUniformMatrix3x2dvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLboolean, GLfloat*, void> glProgramUniformMatrix3x2fvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLboolean, GLdouble*, void> glProgramUniformMatrix3x4dvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLboolean, GLfloat*, void> glProgramUniformMatrix3x4fvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLboolean, GLdouble*, void> glProgramUniformMatrix4dvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLboolean, GLfloat*, void> glProgramUniformMatrix4fvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLboolean, GLdouble*, void> glProgramUniformMatrix4x2dvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLboolean, GLfloat*, void> glProgramUniformMatrix4x2fvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLboolean, GLdouble*, void> glProgramUniformMatrix4x3dvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLboolean, GLfloat*, void> glProgramUniformMatrix4x3fvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<ClientAttribMask, void> glPushClientAttribDefaultEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, SizedInternalFormat, GLbuffer, void> glTextureBufferEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, SizedInternalFormat, GLbuffer, GLintptr, GLsizeiptr, void> glTextureBufferRangeEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, GLint, InternalFormat, GLsizei, GLint, PixelFormat, PixelType, void*, void> glTextureImage1DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, GLint, InternalFormat, GLsizei, GLsizei, GLint, PixelFormat, PixelType, void*, void> glTextureImage2DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, GLint, InternalFormat, GLsizei, GLsizei, GLsizei, GLint, PixelFormat, PixelType, void*, void> glTextureImage3DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLboolean, void> glTexturePageCommitmentEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, TextureParameter, GLfloat, void> glTextureParameterfEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, TextureParameter, GLfloat*, void> glTextureParameterfvEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, TextureParameter, GLint, void> glTextureParameteriEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, TextureParameter, GLint*, void> glTextureParameterIivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, TextureParameter, GLuint*, void> glTextureParameterIuivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, TextureParameter, GLint*, void> glTextureParameterivEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, GLrenderbuffer, void> glTextureRenderbufferEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, GLenum, GLsizei, SizedInternalFormat, GLsizei, void> glTextureStorage1DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, GLenum, GLsizei, SizedInternalFormat, GLsizei, GLsizei, void> glTextureStorage2DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, GLsizei, SizedInternalFormat, GLsizei, GLsizei, GLboolean, void> glTextureStorage2DMultisampleEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, GLenum, GLsizei, SizedInternalFormat, GLsizei, GLsizei, GLsizei, void> glTextureStorage3DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, GLenum, GLsizei, SizedInternalFormat, GLsizei, GLsizei, GLsizei, GLboolean, void> glTextureStorage3DMultisampleEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, GLint, GLint, GLsizei, PixelFormat, PixelType, void*, void> glTextureSubImage1DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, GLint, GLint, GLint, GLsizei, GLsizei, PixelFormat, PixelType, void*, void> glTextureSubImage2DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureTarget, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, PixelFormat, PixelType, void*, void> glTextureSubImage3DEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLbuffer, GLboolean> glUnmapNamedBufferEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLuint, GLbuffer, GLintptr, GLsizei, void> glVertexArrayBindVertexBufferEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLbuffer, GLint, ColorPointerType, GLsizei, GLintptr, void> glVertexArrayColorOffsetEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLbuffer, GLsizei, GLintptr, void> glVertexArrayEdgeFlagOffsetEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLbuffer, FogCoordinatePointerType, GLsizei, GLintptr, void> glVertexArrayFogCoordOffsetEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLbuffer, IndexPointerType, GLsizei, GLintptr, void> glVertexArrayIndexOffsetEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLbuffer, GLenum, GLint, TexCoordPointerType, GLsizei, GLintptr, void> glVertexArrayMultiTexCoordOffsetEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLbuffer, NormalPointerType, GLsizei, GLintptr, void> glVertexArrayNormalOffsetEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLbuffer, GLint, ColorPointerType, GLsizei, GLintptr, void> glVertexArraySecondaryColorOffsetEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLbuffer, GLint, TexCoordPointerType, GLsizei, GLintptr, void> glVertexArrayTexCoordOffsetEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLuint, GLuint, void> glVertexArrayVertexAttribBindingEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLuint, GLuint, void> glVertexArrayVertexAttribDivisorEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLuint, GLint, VertexAttribType, GLboolean, GLuint, void> glVertexArrayVertexAttribFormatEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLuint, GLint, VertexAttribType, GLuint, void> glVertexArrayVertexAttribIFormatEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLbuffer, GLuint, GLint, VertexAttribType, GLsizei, GLintptr, void> glVertexArrayVertexAttribIOffsetEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLuint, GLint, VertexAttribType, GLuint, void> glVertexArrayVertexAttribLFormatEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLbuffer, GLuint, GLint, VertexAttribType, GLsizei, GLintptr, void> glVertexArrayVertexAttribLOffsetEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLbuffer, GLuint, GLint, VertexAttribType, GLboolean, GLsizei, GLintptr, void> glVertexArrayVertexAttribOffsetEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLuint, GLuint, void> glVertexArrayVertexBindingDivisorEXT;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLbuffer, GLint, VertexPointerType, GLsizei, GLintptr, void> glVertexArrayVertexOffsetEXT;
    }
}

#endif