public enum ProgramProperty : GLenum {
    DeleteStatus = gl.Constants.GL_DELETE_STATUS,
    LinkStatus = gl.Constants.GL_LINK_STATUS,
    ValidateStatus = gl.Constants.GL_VALIDATE_STATUS,
    InfoLogLength = gl.Constants.GL_INFO_LOG_LENGTH,
    AttachedShaders = gl.Constants.GL_ATTACHED_SHADERS,
    ActiveUniforms = gl.Constants.GL_ACTIVE_UNIFORMS,
    ActiveUniformMaxLength = gl.Constants.GL_ACTIVE_UNIFORM_MAX_LENGTH,
    ActiveAttributes = gl.Constants.GL_ACTIVE_ATTRIBUTES,
    ActiveAttributeMaxLength = gl.Constants.GL_ACTIVE_ATTRIBUTE_MAX_LENGTH,
    TransformFeedbackVaryingMaxLength = gl.Constants.GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH,
    TransformFeedbackBufferMode = gl.Constants.GL_TRANSFORM_FEEDBACK_BUFFER_MODE,
    TransformFeedbackVaryings = gl.Constants.GL_TRANSFORM_FEEDBACK_VARYINGS,
    ActiveUniformBlockMaxNameLength = gl.Constants.GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH,
    ActiveUniformBlocks = gl.Constants.GL_ACTIVE_UNIFORM_BLOCKS,
    GeometryVerticesOut = gl.Constants.GL_GEOMETRY_VERTICES_OUT,
    GeometryInputType = gl.Constants.GL_GEOMETRY_INPUT_TYPE,
    GeometryOutputType = gl.Constants.GL_GEOMETRY_OUTPUT_TYPE,
    ProgramBinaryLength = gl.Constants.GL_PROGRAM_BINARY_LENGTH,
    ActiveAtomicCounterBuffers = gl.Constants.GL_ACTIVE_ATOMIC_COUNTER_BUFFERS,
    ComputeWorkGroupSize = gl.Constants.GL_COMPUTE_WORK_GROUP_SIZE,
}
