public enum BlendingFactor : GLenum {
    Zero = gl.Constants.GL_ZERO,
    One = gl.Constants.GL_ONE,
    SrcColor = gl.Constants.GL_SRC_COLOR,
    OneMinusSrcColor = gl.Constants.GL_ONE_MINUS_SRC_COLOR,
    SrcAlpha = gl.Constants.GL_SRC_ALPHA,
    OneMinusSrcAlpha = gl.Constants.GL_ONE_MINUS_SRC_ALPHA,
    DstAlpha = gl.Constants.GL_DST_ALPHA,
    OneMinusDstAlpha = gl.Constants.GL_ONE_MINUS_DST_ALPHA,
    DstColor = gl.Constants.GL_DST_COLOR,
    OneMinusDstColor = gl.Constants.GL_ONE_MINUS_DST_COLOR,
    SrcAlphaSaturate = gl.Constants.GL_SRC_ALPHA_SATURATE,
    ConstantColor = gl.Constants.GL_CONSTANT_COLOR,
    OneMinusConstantColor = gl.Constants.GL_ONE_MINUS_CONSTANT_COLOR,
    ConstantAlpha = gl.Constants.GL_CONSTANT_ALPHA,
    OneMinusConstantAlpha = gl.Constants.GL_ONE_MINUS_CONSTANT_ALPHA,
    Src1Alpha = gl.Constants.GL_SRC1_ALPHA,
    Src1Color = gl.Constants.GL_SRC1_COLOR,
    OneMinusSrc1Color = gl.Constants.GL_ONE_MINUS_SRC1_COLOR,
    OneMinusSrc1Alpha = gl.Constants.GL_ONE_MINUS_SRC1_ALPHA,
}
