public enum GLCapability : GLenum {
    LineSmooth = gl.Constants.GL_LINE_SMOOTH,
    PolygonSmooth = gl.Constants.GL_POLYGON_SMOOTH,
    CullFace = gl.Constants.GL_CULL_FACE,
    DepthTest = gl.Constants.GL_DEPTH_TEST,
    StencilTest = gl.Constants.GL_STENCIL_TEST,
    Dither = gl.Constants.GL_DITHER,
    Blend = gl.Constants.GL_BLEND,
    ScissorTest = gl.Constants.GL_SCISSOR_TEST,
    Texture1D = gl.Constants.GL_TEXTURE_1D,
    Texture2D = gl.Constants.GL_TEXTURE_2D,
    ColorLogicOp = gl.Constants.GL_COLOR_LOGIC_OP,
    PolygonOffsetPoint = gl.Constants.GL_POLYGON_OFFSET_POINT,
    PolygonOffsetLine = gl.Constants.GL_POLYGON_OFFSET_LINE,
    PolygonOffsetFill = gl.Constants.GL_POLYGON_OFFSET_FILL,
    VertexArray = gl.Constants.GL_VERTEX_ARRAY,
    Multisample = gl.Constants.GL_MULTISAMPLE,
    SampleAlphaToCoverage = gl.Constants.GL_SAMPLE_ALPHA_TO_COVERAGE,
    SampleAlphaToOne = gl.Constants.GL_SAMPLE_ALPHA_TO_ONE,
    SampleCoverage = gl.Constants.GL_SAMPLE_COVERAGE,
    TextureCubeMap = gl.Constants.GL_TEXTURE_CUBE_MAP,
    ClipDistance0 = gl.Constants.GL_CLIP_DISTANCE0,
    ClipDistance1 = gl.Constants.GL_CLIP_DISTANCE1,
    ClipDistance2 = gl.Constants.GL_CLIP_DISTANCE2,
    ClipDistance3 = gl.Constants.GL_CLIP_DISTANCE3,
    ClipDistance4 = gl.Constants.GL_CLIP_DISTANCE4,
    ClipDistance5 = gl.Constants.GL_CLIP_DISTANCE5,
    ClipDistance6 = gl.Constants.GL_CLIP_DISTANCE6,
    ClipDistance7 = gl.Constants.GL_CLIP_DISTANCE7,
    RasterizerDiscard = gl.Constants.GL_RASTERIZER_DISCARD,
    FramebufferSrgb = gl.Constants.GL_FRAMEBUFFER_SRGB,
    TextureRectangle = gl.Constants.GL_TEXTURE_RECTANGLE,
    PrimitiveRestart = gl.Constants.GL_PRIMITIVE_RESTART,
    ProgramPointSize = gl.Constants.GL_PROGRAM_POINT_SIZE,
    DepthClamp = gl.Constants.GL_DEPTH_CLAMP,
    TextureCubeMapSeamless = gl.Constants.GL_TEXTURE_CUBE_MAP_SEAMLESS,
    SampleMask = gl.Constants.GL_SAMPLE_MASK,
    SampleShading = gl.Constants.GL_SAMPLE_SHADING,
    PrimitiveRestartFixedIndex = gl.Constants.GL_PRIMITIVE_RESTART_FIXED_INDEX,
    DebugOutputSynchronous = gl.Constants.GL_DEBUG_OUTPUT_SYNCHRONOUS,
    DebugOutput = gl.Constants.GL_DEBUG_OUTPUT,
#if GL_NV_primitive_shading_rate
    ShadingRateImagePerPrimitiveNv = gl.Constants.GL_SHADING_RATE_IMAGE_PER_PRIMITIVE_NV,
#endif
}
