public enum PixelFormat : GLenum {
    UnsignedShort = gl.Constants.GL_UNSIGNED_SHORT,
    UnsignedInt = gl.Constants.GL_UNSIGNED_INT,
    StencilIndex = gl.Constants.GL_STENCIL_INDEX,
    DepthComponent = gl.Constants.GL_DEPTH_COMPONENT,
    Red = gl.Constants.GL_RED,
    Green = gl.Constants.GL_GREEN,
    Blue = gl.Constants.GL_BLUE,
    Alpha = gl.Constants.GL_ALPHA,
    Rgb = gl.Constants.GL_RGB,
    Rgba = gl.Constants.GL_RGBA,
    Bgr = gl.Constants.GL_BGR,
    Bgra = gl.Constants.GL_BGRA,
    RedInteger = gl.Constants.GL_RED_INTEGER,
    GreenInteger = gl.Constants.GL_GREEN_INTEGER,
    BlueInteger = gl.Constants.GL_BLUE_INTEGER,
    RgbInteger = gl.Constants.GL_RGB_INTEGER,
    RgbaInteger = gl.Constants.GL_RGBA_INTEGER,
    BgrInteger = gl.Constants.GL_BGR_INTEGER,
    BgraInteger = gl.Constants.GL_BGRA_INTEGER,
    DepthStencil = gl.Constants.GL_DEPTH_STENCIL,
    Rg = gl.Constants.GL_RG,
    RgInteger = gl.Constants.GL_RG_INTEGER,
}
