public enum PixelStoreParameter : GLenum {
    UnpackSwapBytes = gl.Constants.GL_UNPACK_SWAP_BYTES,
    UnpackLsbFirst = gl.Constants.GL_UNPACK_LSB_FIRST,
    UnpackRowLength = gl.Constants.GL_UNPACK_ROW_LENGTH,
    UnpackSkipRows = gl.Constants.GL_UNPACK_SKIP_ROWS,
    UnpackSkipPixels = gl.Constants.GL_UNPACK_SKIP_PIXELS,
    UnpackAlignment = gl.Constants.GL_UNPACK_ALIGNMENT,
    PackSwapBytes = gl.Constants.GL_PACK_SWAP_BYTES,
    PackLsbFirst = gl.Constants.GL_PACK_LSB_FIRST,
    PackRowLength = gl.Constants.GL_PACK_ROW_LENGTH,
    PackSkipRows = gl.Constants.GL_PACK_SKIP_ROWS,
    PackSkipPixels = gl.Constants.GL_PACK_SKIP_PIXELS,
    PackAlignment = gl.Constants.GL_PACK_ALIGNMENT,
    PackSkipImages = gl.Constants.GL_PACK_SKIP_IMAGES,
    PackImageHeight = gl.Constants.GL_PACK_IMAGE_HEIGHT,
    UnpackSkipImages = gl.Constants.GL_UNPACK_SKIP_IMAGES,
    UnpackImageHeight = gl.Constants.GL_UNPACK_IMAGE_HEIGHT,
}
