public enum ReadBufferMode : GLenum {
    None = gl.Constants.GL_NONE,
    FrontLeft = gl.Constants.GL_FRONT_LEFT,
    FrontRight = gl.Constants.GL_FRONT_RIGHT,
    BackLeft = gl.Constants.GL_BACK_LEFT,
    BackRight = gl.Constants.GL_BACK_RIGHT,
    Front = gl.Constants.GL_FRONT,
    Back = gl.Constants.GL_BACK,
    Left = gl.Constants.GL_LEFT,
    Right = gl.Constants.GL_RIGHT,
    ColorAttachment0 = gl.Constants.GL_COLOR_ATTACHMENT0,
    ColorAttachment1 = gl.Constants.GL_COLOR_ATTACHMENT1,
    ColorAttachment2 = gl.Constants.GL_COLOR_ATTACHMENT2,
    ColorAttachment3 = gl.Constants.GL_COLOR_ATTACHMENT3,
    ColorAttachment4 = gl.Constants.GL_COLOR_ATTACHMENT4,
    ColorAttachment5 = gl.Constants.GL_COLOR_ATTACHMENT5,
    ColorAttachment6 = gl.Constants.GL_COLOR_ATTACHMENT6,
    ColorAttachment7 = gl.Constants.GL_COLOR_ATTACHMENT7,
    ColorAttachment8 = gl.Constants.GL_COLOR_ATTACHMENT8,
    ColorAttachment9 = gl.Constants.GL_COLOR_ATTACHMENT9,
    ColorAttachment10 = gl.Constants.GL_COLOR_ATTACHMENT10,
    ColorAttachment11 = gl.Constants.GL_COLOR_ATTACHMENT11,
    ColorAttachment12 = gl.Constants.GL_COLOR_ATTACHMENT12,
    ColorAttachment13 = gl.Constants.GL_COLOR_ATTACHMENT13,
    ColorAttachment14 = gl.Constants.GL_COLOR_ATTACHMENT14,
    ColorAttachment15 = gl.Constants.GL_COLOR_ATTACHMENT15,
}
