public partial class gl { 
    public partial class Functions { 
        public static unsafe delegate* unmanaged[Cdecl]<GLuint, GLtexture, void> glBindTextureUnit;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, GLframebuffer, GLint, GLint, GLint, GLint, GLint, GLint, GLint, GLint, ClearBufferMask, MagFilter, void> glBlitNamedFramebuffer;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, FramebufferTarget, FramebufferStatus> glCheckNamedFramebufferStatus;
        public static unsafe delegate* unmanaged[Cdecl]<GLbuffer, SizedInternalFormat, PixelFormat, PixelType, void*, void> glClearNamedBufferData;
        public static unsafe delegate* unmanaged[Cdecl]<GLbuffer, SizedInternalFormat, GLintptr, GLsizeiptr, PixelFormat, PixelType, void*, void> glClearNamedBufferSubData;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, Buffer, GLint, GLfloat, GLint, void> glClearNamedFramebufferfi;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, Buffer, GLint, GLfloat*, void> glClearNamedFramebufferfv;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, Buffer, GLint, GLint*, void> glClearNamedFramebufferiv;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, Buffer, GLint, GLuint*, void> glClearNamedFramebufferuiv;
        public static unsafe delegate* unmanaged[Cdecl]<ClipControlOrigin, ClipControlDepth, void> glClipControl;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, GLint, GLint, GLsizei, InternalFormat, GLsizei, void*, void> glCompressedTextureSubImage1D;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, GLint, GLint, GLint, GLsizei, GLsizei, InternalFormat, GLsizei, void*, void> glCompressedTextureSubImage2D;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, InternalFormat, GLsizei, void*, void> glCompressedTextureSubImage3D;
        public static unsafe delegate* unmanaged[Cdecl]<GLbuffer, GLbuffer, GLintptr, GLintptr, GLsizeiptr, void> glCopyNamedBufferSubData;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, GLint, GLint, GLint, GLint, GLsizei, void> glCopyTextureSubImage1D;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei, void> glCopyTextureSubImage2D;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, GLint, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei, void> glCopyTextureSubImage3D;
        public static unsafe delegate* unmanaged[Cdecl]<GLsizei, GLbuffer*, void> glCreateBuffers;
        public static unsafe delegate* unmanaged[Cdecl]<GLsizei, GLframebuffer*, void> glCreateFramebuffers;
        public static unsafe delegate* unmanaged[Cdecl]<GLsizei, GLprogrampipeline*, void> glCreateProgramPipelines;
        public static unsafe delegate* unmanaged[Cdecl]<QueryTarget, GLsizei, GLquery*, void> glCreateQueries;
        public static unsafe delegate* unmanaged[Cdecl]<GLsizei, GLrenderbuffer*, void> glCreateRenderbuffers;
        public static unsafe delegate* unmanaged[Cdecl]<GLsizei, GLsampler*, void> glCreateSamplers;
        public static unsafe delegate* unmanaged[Cdecl]<TextureTarget, GLsizei, GLtexture*, void> glCreateTextures;
        public static unsafe delegate* unmanaged[Cdecl]<GLsizei, GLtransformfeedback*, void> glCreateTransformFeedbacks;
        public static unsafe delegate* unmanaged[Cdecl]<GLsizei, GLvertexarray*, void> glCreateVertexArrays;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLuint, void> glDisableVertexArrayAttrib;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLuint, void> glEnableVertexArrayAttrib;
        public static unsafe delegate* unmanaged[Cdecl]<GLbuffer, GLintptr, GLsizeiptr, void> glFlushMappedNamedBufferRange;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, void> glGenerateTextureMipmap;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, GLint, GLsizei, void*, void> glGetCompressedTextureImage;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLsizei, void*, void> glGetCompressedTextureSubImage;
        public static unsafe delegate* unmanaged[Cdecl]<GraphicsResetStatus> glGetGraphicsResetStatus;
        public static unsafe delegate* unmanaged[Cdecl]<GLbuffer, BufferParameter, GLint64*, void> glGetNamedBufferParameteri64v;
        public static unsafe delegate* unmanaged[Cdecl]<GLbuffer, BufferParameter, GLint*, void> glGetNamedBufferParameteriv;
        public static unsafe delegate* unmanaged[Cdecl]<GLbuffer, BufferPointerParameter, void**, void> glGetNamedBufferPointerv;
        public static unsafe delegate* unmanaged[Cdecl]<GLbuffer, GLintptr, GLsizeiptr, void*, void> glGetNamedBufferSubData;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, FramebufferAttachment, FramebufferAttachmentParameter, GLint*, void> glGetNamedFramebufferAttachmentParameteriv;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, FramebufferParameter, GLint*, void> glGetNamedFramebufferParameteriv;
        public static unsafe delegate* unmanaged[Cdecl]<GLrenderbuffer, RenderbufferParameter, GLint*, void> glGetNamedRenderbufferParameteriv;
        public static unsafe delegate* unmanaged[Cdecl]<TextureTarget, GLint, GLsizei, void*, void> glGetnCompressedTexImage;
        public static unsafe delegate* unmanaged[Cdecl]<TextureTarget, GLint, PixelFormat, PixelType, GLsizei, void*, void> glGetnTexImage;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLdouble*, void> glGetnUniformdv;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLfloat*, void> glGetnUniformfv;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLint*, void> glGetnUniformiv;
        public static unsafe delegate* unmanaged[Cdecl]<GLprogram, GLint, GLsizei, GLuint*, void> glGetnUniformuiv;
        public static unsafe delegate* unmanaged[Cdecl]<GLquery, GLbuffer, QueryObjectParameter, GLintptr, void> glGetQueryBufferObjecti64v;
        public static unsafe delegate* unmanaged[Cdecl]<GLquery, GLbuffer, QueryObjectParameter, GLintptr, void> glGetQueryBufferObjectiv;
        public static unsafe delegate* unmanaged[Cdecl]<GLquery, GLbuffer, QueryObjectParameter, GLintptr, void> glGetQueryBufferObjectui64v;
        public static unsafe delegate* unmanaged[Cdecl]<GLquery, GLbuffer, QueryObjectParameter, GLintptr, void> glGetQueryBufferObjectuiv;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, GLint, PixelFormat, PixelType, GLsizei, void*, void> glGetTextureImage;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, GLint, TextureParameter, GLfloat*, void> glGetTextureLevelParameterfv;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, GLint, TextureParameter, GLint*, void> glGetTextureLevelParameteriv;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureParameter, GLfloat*, void> glGetTextureParameterfv;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureParameter, GLint*, void> glGetTextureParameterIiv;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureParameter, GLuint*, void> glGetTextureParameterIuiv;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureParameter, GLint*, void> glGetTextureParameteriv;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, PixelFormat, PixelType, GLsizei, void*, void> glGetTextureSubImage;
        public static unsafe delegate* unmanaged[Cdecl]<GLtransformfeedback, TransformFeedbackParameter, GLuint, GLint*, void> glGetTransformFeedbacki_v;
        public static unsafe delegate* unmanaged[Cdecl]<GLtransformfeedback, TransformFeedbackParameter, GLuint, GLint64*, void> glGetTransformFeedbacki64_v;
        public static unsafe delegate* unmanaged[Cdecl]<GLtransformfeedback, TransformFeedbackParameter, GLint*, void> glGetTransformFeedbackiv;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLuint, VertexArrayParameter, GLint64*, void> glGetVertexArrayIndexed64iv;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLuint, VertexArrayParameter, GLint*, void> glGetVertexArrayIndexediv;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, VertexArrayParameter, GLint*, void> glGetVertexArrayiv;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, GLsizei, FramebufferAttachment*, void> glInvalidateNamedFramebufferData;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, GLsizei, FramebufferAttachment*, GLint, GLint, GLsizei, GLsizei, void> glInvalidateNamedFramebufferSubData;
        public static unsafe delegate* unmanaged[Cdecl]<GLbuffer, BufferAccess, void*> glMapNamedBuffer;
        public static unsafe delegate* unmanaged[Cdecl]<GLbuffer, GLintptr, GLsizeiptr, MapBufferAccessMask, void*> glMapNamedBufferRange;
        public static unsafe delegate* unmanaged[Cdecl]<MemoryBarrierMask, void> glMemoryBarrierByRegion;
        public static unsafe delegate* unmanaged[Cdecl]<GLbuffer, GLsizeiptr, void*, BufferUsage, void> glNamedBufferData;
        public static unsafe delegate* unmanaged[Cdecl]<GLbuffer, GLsizeiptr, void*, BufferStorageMask, void> glNamedBufferStorage;
        public static unsafe delegate* unmanaged[Cdecl]<GLbuffer, GLintptr, GLsizeiptr, void*, void> glNamedBufferSubData;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, ColorBuffer, void> glNamedFramebufferDrawBuffer;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, GLsizei, ColorBuffer*, void> glNamedFramebufferDrawBuffers;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, FramebufferParameter, GLint, void> glNamedFramebufferParameteri;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, ColorBuffer, void> glNamedFramebufferReadBuffer;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, FramebufferAttachment, RenderbufferTarget, GLrenderbuffer, void> glNamedFramebufferRenderbuffer;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, FramebufferAttachment, GLtexture, GLint, void> glNamedFramebufferTexture;
        public static unsafe delegate* unmanaged[Cdecl]<GLframebuffer, FramebufferAttachment, GLtexture, GLint, GLint, void> glNamedFramebufferTextureLayer;
        public static unsafe delegate* unmanaged[Cdecl]<GLrenderbuffer, InternalFormat, GLsizei, GLsizei, void> glNamedRenderbufferStorage;
        public static unsafe delegate* unmanaged[Cdecl]<GLrenderbuffer, GLsizei, InternalFormat, GLsizei, GLsizei, void> glNamedRenderbufferStorageMultisample;
        public static unsafe delegate* unmanaged[Cdecl]<GLint, GLint, GLsizei, GLsizei, PixelFormat, PixelType, GLsizei, void*, void> glReadnPixels;
        public static unsafe delegate* unmanaged[Cdecl]<void> glTextureBarrier;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, SizedInternalFormat, GLbuffer, void> glTextureBuffer;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, SizedInternalFormat, GLbuffer, GLintptr, GLsizeiptr, void> glTextureBufferRange;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureParameter, GLfloat, void> glTextureParameterf;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureParameter, GLfloat*, void> glTextureParameterfv;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureParameter, GLint, void> glTextureParameteri;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureParameter, GLint*, void> glTextureParameterIiv;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureParameter, GLuint*, void> glTextureParameterIuiv;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, TextureParameter, GLint*, void> glTextureParameteriv;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, GLsizei, SizedInternalFormat, GLsizei, void> glTextureStorage1D;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, GLsizei, SizedInternalFormat, GLsizei, GLsizei, void> glTextureStorage2D;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, GLsizei, SizedInternalFormat, GLsizei, GLsizei, GLboolean, void> glTextureStorage2DMultisample;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, GLsizei, SizedInternalFormat, GLsizei, GLsizei, GLsizei, void> glTextureStorage3D;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, GLsizei, SizedInternalFormat, GLsizei, GLsizei, GLsizei, GLboolean, void> glTextureStorage3DMultisample;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, GLint, GLint, GLsizei, PixelFormat, PixelType, void*, void> glTextureSubImage1D;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, GLint, GLint, GLint, GLsizei, GLsizei, PixelFormat, PixelType, void*, void> glTextureSubImage2D;
        public static unsafe delegate* unmanaged[Cdecl]<GLtexture, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, PixelFormat, PixelType, void*, void> glTextureSubImage3D;
        public static unsafe delegate* unmanaged[Cdecl]<GLtransformfeedback, GLuint, GLbuffer, void> glTransformFeedbackBufferBase;
        public static unsafe delegate* unmanaged[Cdecl]<GLtransformfeedback, GLuint, GLbuffer, GLintptr, GLsizeiptr, void> glTransformFeedbackBufferRange;
        public static unsafe delegate* unmanaged[Cdecl]<GLbuffer, GLboolean> glUnmapNamedBuffer;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLuint, GLuint, void> glVertexArrayAttribBinding;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLuint, GLint, VertexAttribType, GLboolean, GLuint, void> glVertexArrayAttribFormat;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLuint, GLint, VertexAttribType, GLuint, void> glVertexArrayAttribIFormat;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLuint, GLint, VertexAttribType, GLuint, void> glVertexArrayAttribLFormat;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLuint, GLuint, void> glVertexArrayBindingDivisor;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLbuffer, void> glVertexArrayElementBuffer;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLuint, GLbuffer, GLintptr, GLsizei, void> glVertexArrayVertexBuffer;
        public static unsafe delegate* unmanaged[Cdecl]<GLvertexarray, GLuint, GLsizei, GLbuffer*, GLintptr*, GLsizei*, void> glVertexArrayVertexBuffers;
    }
}
